// Расширенная база данных английских слов - 1500+ слов

export type Level = 'beginner' | 'elementary' | 'pre-intermediate' | 'intermediate' | 'upper-intermediate';

export interface Word {
  english: string;
  russian: string;
  kazakh: string;
  category: string;
  level: Level;
  image?: string;
  sentence?: { en: string; ru: string; kz: string };
}

export const VOCABULARY_EXTENDED: Word[] = [
  // ==================== BEGINNER (300+ слов) ====================
  
  // Animals - Животные (40 слов)
  { english: 'cat', russian: 'кот', kazakh: 'мысық', category: 'Animals', level: 'beginner' },
  { english: 'dog', russian: 'собака', kazakh: 'ит', category: 'Animals', level: 'beginner' },
  { english: 'bird', russian: 'птица', kazakh: 'құс', category: 'Animals', level: 'beginner' },
  { english: 'fish', russian: 'рыба', kazakh: 'балық', category: 'Animals', level: 'beginner' },
  { english: 'rabbit', russian: 'кролик', kazakh: 'қоян', category: 'Animals', level: 'beginner' },
  { english: 'horse', russian: 'лошадь', kazakh: 'жылқы', category: 'Animals', level: 'beginner' },
  { english: 'cow', russian: 'корова', kazakh: 'сиыр', category: 'Animals', level: 'beginner' },
  { english: 'pig', russian: 'свинья', kazakh: 'шошқа', category: 'Animals', level: 'beginner' },
  { english: 'chicken', russian: 'курица', kazakh: 'тауық', category: 'Animals', level: 'beginner' },
  { english: 'duck', russian: 'утка', kazakh: 'үйрек', category: 'Animals', level: 'beginner' },
  { english: 'goat', russian: 'коза', kazakh: 'ешкі', category: 'Animals', level: 'beginner' },
  { english: 'sheep', russian: 'овца', kazakh: 'қой', category: 'Animals', level: 'beginner' },
  { english: 'elephant', russian: 'слон', kazakh: 'піл', category: 'Animals', level: 'beginner' },
  { english: 'lion', russian: 'лев', kazakh: 'арыстан', category: 'Animals', level: 'beginner' },
  { english: 'tiger', russian: 'тигр', kazakh: 'жолбарыс', category: 'Animals', level: 'beginner' },
  { english: 'bear', russian: 'медведь', kazakh: 'аю', category: 'Animals', level: 'beginner' },
  { english: 'wolf', russian: 'волк', kazakh: 'қасқыр', category: 'Animals', level: 'beginner' },
  { english: 'fox', russian: 'лиса', kazakh: 'түлкі', category: 'Animals', level: 'beginner' },
  { english: 'monkey', russian: 'обезьяна', kazakh: 'маймыл', category: 'Animals', level: 'beginner' },
  { english: 'giraffe', russian: 'жираф', kazakh: 'керік', category: 'Animals', level: 'beginner' },
  { english: 'zebra', russian: 'зебра', kazakh: 'зебра', category: 'Animals', level: 'beginner' },
  { english: 'mouse', russian: 'мышь', kazakh: 'тышқан', category: 'Animals', level: 'beginner' },
  { english: 'rat', russian: 'крыса', kazakh: 'егеуқұйрық', category: 'Animals', level: 'beginner' },
  { english: 'frog', russian: 'лягушка', kazakh: 'бақа', category: 'Animals', level: 'beginner' },
  { english: 'snake', russian: 'змея', kazakh: 'жылан', category: 'Animals', level: 'beginner' },
  { english: 'turtle', russian: 'черепаха', kazakh: 'тасбақа', category: 'Animals', level: 'beginner' },
  { english: 'butterfly', russian: 'бабочка', kazakh: 'көбелек', category: 'Animals', level: 'beginner' },
  { english: 'bee', russian: 'пчела', kazakh: 'ара', category: 'Animals', level: 'beginner' },
  { english: 'spider', russian: 'паук', kazakh: 'өрмекші', category: 'Animals', level: 'beginner' },
  { english: 'ant', russian: 'муравей', kazakh: 'құмырсқа', category: 'Animals', level: 'beginner' },
  { english: 'fly', russian: 'муха', kazakh: 'шыбын', category: 'Animals', level: 'beginner' },
  { english: 'ladybug', russian: 'божья коровка', kazakh: 'қоңыз', category: 'Animals', level: 'beginner' },
  { english: 'snail', russian: 'улитка', kazakh: 'ұлу', category: 'Animals', level: 'beginner' },
  { english: 'dolphin', russian: 'дельфин', kazakh: 'дельфин', category: 'Animals', level: 'beginner' },
  { english: 'whale', russian: 'кит', kazakh: 'кит', category: 'Animals', level: 'beginner' },
  { english: 'shark', russian: 'акула', kazakh: 'акула', category: 'Animals', level: 'beginner' },
  { english: 'octopus', russian: 'осьминог', kazakh: 'сегізаяқ', category: 'Animals', level: 'beginner' },
  { english: 'crab', russian: 'краб', kazakh: 'шаян', category: 'Animals', level: 'beginner' },
  { english: 'penguin', russian: 'пингвин', kazakh: 'пингвин', category: 'Animals', level: 'beginner' },
  { english: 'parrot', russian: 'попугай', kazakh: 'тотықұс', category: 'Animals', level: 'beginner' },

  // Colors - Цвета (20 слов)
  { english: 'red', russian: 'красный', kazakh: 'қызыл', category: 'Colors', level: 'beginner' },
  { english: 'blue', russian: 'синий', kazakh: 'көк', category: 'Colors', level: 'beginner' },
  { english: 'green', russian: 'зеленый', kazakh: 'жасыл', category: 'Colors', level: 'beginner' },
  { english: 'yellow', russian: 'желтый', kazakh: 'сары', category: 'Colors', level: 'beginner' },
  { english: 'black', russian: 'черный', kazakh: 'қара', category: 'Colors', level: 'beginner' },
  { english: 'white', russian: 'белый', kazakh: 'ақ', category: 'Colors', level: 'beginner' },
  { english: 'orange', russian: 'оранжевый', kazakh: 'сарғыш', category: 'Colors', level: 'beginner' },
  { english: 'purple', russian: 'фиолетовый', kazakh: 'күлгін', category: 'Colors', level: 'beginner' },
  { english: 'pink', russian: 'розовый', kazakh: 'қызғылт', category: 'Colors', level: 'beginner' },
  { english: 'brown', russian: 'коричневый', kazakh: 'қоңыр', category: 'Colors', level: 'beginner' },
  { english: 'gray', russian: 'серый', kazakh: 'сұр', category: 'Colors', level: 'beginner' },
  { english: 'silver', russian: 'серебряный', kazakh: 'күміс', category: 'Colors', level: 'beginner' },
  { english: 'gold', russian: 'золотой', kazakh: 'алтын', category: 'Colors', level: 'beginner' },
  { english: 'light', russian: 'светлый', kazakh: 'ашық', category: 'Colors', level: 'beginner' },
  { english: 'dark', russian: 'темный', kazakh: 'қою', category: 'Colors', level: 'beginner' },
  { english: 'bright', russian: 'яркий', kazakh: 'жарқын', category: 'Colors', level: 'beginner' },
  { english: 'pale', russian: 'бледный', kazakh: 'ашық түсті', category: 'Colors', level: 'beginner' },
  { english: 'colorful', russian: 'красочный', kazakh: 'түрлі-түсті', category: 'Colors', level: 'beginner' },
  { english: 'transparent', russian: 'прозрачный', kazakh: 'мөлдір', category: 'Colors', level: 'beginner' },
  { english: 'shiny', russian: 'блестящий', kazakh: 'жылтыр', category: 'Colors', level: 'beginner' },

  // Numbers - Числа (30 слов)
  { english: 'zero', russian: 'ноль', kazakh: 'нөл', category: 'Numbers', level: 'beginner' },
  { english: 'one', russian: 'один', kazakh: 'бір', category: 'Numbers', level: 'beginner' },
  { english: 'two', russian: 'два', kazakh: 'екі', category: 'Numbers', level: 'beginner' },
  { english: 'three', russian: 'три', kazakh: 'үш', category: 'Numbers', level: 'beginner' },
  { english: 'four', russian: 'четыре', kazakh: 'төрт', category: 'Numbers', level: 'beginner' },
  { english: 'five', russian: 'пять', kazakh: 'бес', category: 'Numbers', level: 'beginner' },
  { english: 'six', russian: 'шесть', kazakh: 'алты', category: 'Numbers', level: 'beginner' },
  { english: 'seven', russian: 'семь', kazakh: 'жеті', category: 'Numbers', level: 'beginner' },
  { english: 'eight', russian: 'восемь', kazakh: 'сегіз', category: 'Numbers', level: 'beginner' },
  { english: 'nine', russian: 'девять', kazakh: 'тоғыз', category: 'Numbers', level: 'beginner' },
  { english: 'ten', russian: 'десять', kazakh: 'он', category: 'Numbers', level: 'beginner' },
  { english: 'eleven', russian: 'одиннадцать', kazakh: 'он бір', category: 'Numbers', level: 'beginner' },
  { english: 'twelve', russian: 'двенадцать', kazakh: 'он екі', category: 'Numbers', level: 'beginner' },
  { english: 'thirteen', russian: 'тринадцать', kazakh: 'он үш', category: 'Numbers', level: 'beginner' },
  { english: 'fourteen', russian: 'четырнадцать', kazakh: 'он төрт', category: 'Numbers', level: 'beginner' },
  { english: 'fifteen', russian: 'пятнадцать', kazakh: 'он бес', category: 'Numbers', level: 'beginner' },
  { english: 'sixteen', russian: 'шестнадцать', kazakh: 'он алты', category: 'Numbers', level: 'beginner' },
  { english: 'seventeen', russian: 'семнадцать', kazakh: 'он жеті', category: 'Numbers', level: 'beginner' },
  { english: 'eighteen', russian: 'восемнадцать', kazakh: 'он сегіз', category: 'Numbers', level: 'beginner' },
  { english: 'nineteen', russian: 'девятнадцать', kazakh: 'он тоғыз', category: 'Numbers', level: 'beginner' },
  { english: 'twenty', russian: 'двадцать', kazakh: 'жиырма', category: 'Numbers', level: 'beginner' },
  { english: 'thirty', russian: 'тридцать', kazakh: 'отыз', category: 'Numbers', level: 'beginner' },
  { english: 'forty', russian: 'сорок', kazakh: 'қырық', category: 'Numbers', level: 'beginner' },
  { english: 'fifty', russian: 'пятьдесят', kazakh: 'елу', category: 'Numbers', level: 'beginner' },
  { english: 'sixty', russian: 'шестьдесят', kazakh: 'алпыс', category: 'Numbers', level: 'beginner' },
  { english: 'seventy', russian: 'семьдесят', kazakh: 'жетпіс', category: 'Numbers', level: 'beginner' },
  { english: 'eighty', russian: 'восемьдесят', kazakh: 'сексен', category: 'Numbers', level: 'beginner' },
  { english: 'ninety', russian: 'девяносто', kazakh: 'тоқсан', category: 'Numbers', level: 'beginner' },
  { english: 'hundred', russian: 'сто', kazakh: 'жүз', category: 'Numbers', level: 'beginner' },
  { english: 'thousand', russian: 'тысяча', kazakh: 'мың', category: 'Numbers', level: 'beginner' },

  // Family - Семья (20 слов)
  { english: 'mother', russian: 'мама', kazakh: 'ана', category: 'Family', level: 'beginner' },
  { english: 'father', russian: 'папа', kazakh: 'әке', category: 'Family', level: 'beginner' },
  { english: 'sister', russian: 'сестра', kazakh: 'әпке/қарындас', category: 'Family', level: 'beginner' },
  { english: 'brother', russian: 'брат', kazakh: 'аға/іні', category: 'Family', level: 'beginner' },
  { english: 'baby', russian: 'малыш', kazakh: 'нәресте', category: 'Family', level: 'beginner' },
  { english: 'grandma', russian: 'бабушка', kazakh: 'әже', category: 'Family', level: 'beginner' },
  { english: 'grandpa', russian: 'дедушка', kazakh: 'ата', category: 'Family', level: 'beginner' },
  { english: 'parents', russian: 'родители', kazakh: 'ата-ана', category: 'Family', level: 'beginner' },
  { english: 'child', russian: 'ребенок', kazakh: 'бала', category: 'Family', level: 'beginner' },
  { english: 'son', russian: 'сын', kazakh: 'ұл', category: 'Family', level: 'beginner' },
  { english: 'daughter', russian: 'дочь', kazakh: 'қыз', category: 'Family', level: 'beginner' },
  { english: 'aunt', russian: 'тетя', kazakh: 'әпке/тәте', category: 'Family', level: 'beginner' },
  { english: 'uncle', russian: 'дядя', kazakh: 'аға/ағай', category: 'Family', level: 'beginner' },
  { english: 'cousin', russian: 'двоюродный брат/сестра', kazakh: 'нағашы', category: 'Family', level: 'beginner' },
  { english: 'husband', russian: 'муж', kazakh: 'күйеу', category: 'Family', level: 'beginner' },
  { english: 'wife', russian: 'жена', kazakh: 'әйел', category: 'Family', level: 'beginner' },
  { english: 'family', russian: 'семья', kazakh: 'отбасы', category: 'Family', level: 'beginner' },
  { english: 'twins', russian: 'близнецы', kazakh: 'егіздер', category: 'Family', level: 'beginner' },
  { english: 'nephew', russian: 'племянник', kazakh: 'жиен', category: 'Family', level: 'beginner' },
  { english: 'niece', russian: 'племянница', kazakh: 'жиен қыз', category: 'Family', level: 'beginner' },

  // Body Parts - Части тела (30 слов)
  { english: 'head', russian: 'голова', kazakh: 'бас', category: 'Body', level: 'beginner' },
  { english: 'hair', russian: 'волосы', kazakh: 'шаш', category: 'Body', level: 'beginner' },
  { english: 'face', russian: 'лицо', kazakh: 'бет', category: 'Body', level: 'beginner' },
  { english: 'eye', russian: 'глаз', kazakh: 'көз', category: 'Body', level: 'beginner' },
  { english: 'ear', russian: 'ухо', kazakh: 'құлақ', category: 'Body', level: 'beginner' },
  { english: 'nose', russian: 'нос', kazakh: 'мұрын', category: 'Body', level: 'beginner' },
  { english: 'mouth', russian: 'рот', kazakh: 'ауыз', category: 'Body', level: 'beginner' },
  { english: 'tooth', russian: 'зуб', kazakh: 'тіс', category: 'Body', level: 'beginner' },
  { english: 'tongue', russian: 'язык', kazakh: 'тіл', category: 'Body', level: 'beginner' },
  { english: 'neck', russian: 'шея', kazakh: 'мойын', category: 'Body', level: 'beginner' },
  { english: 'shoulder', russian: 'плечо', kazakh: 'иық', category: 'Body', level: 'beginner' },
  { english: 'arm', russian: 'рука', kazakh: 'қол', category: 'Body', level: 'beginner' },
  { english: 'hand', russian: 'кисть руки', kazakh: 'алақан', category: 'Body', level: 'beginner' },
  { english: 'finger', russian: 'палец', kazakh: 'саусақ', category: 'Body', level: 'beginner' },
  { english: 'thumb', russian: 'большой палец', kazakh: 'бас бармақ', category: 'Body', level: 'beginner' },
  { english: 'chest', russian: 'грудь', kazakh: 'кеуде', category: 'Body', level: 'beginner' },
  { english: 'back', russian: 'спина', kazakh: 'арқа', category: 'Body', level: 'beginner' },
  { english: 'stomach', russian: 'живот', kazakh: 'қарын', category: 'Body', level: 'beginner' },
  { english: 'leg', russian: 'нога', kazakh: 'аяқ', category: 'Body', level: 'beginner' },
  { english: 'knee', russian: 'колено', kazakh: 'тізе', category: 'Body', level: 'beginner' },
  { english: 'foot', russian: 'ступня', kazakh: 'табан', category: 'Body', level: 'beginner' },
  { english: 'toe', russian: 'палец ноги', kazakh: 'аяқ саусағы', category: 'Body', level: 'beginner' },
  { english: 'heart', russian: 'сердце', kazakh: 'жүрек', category: 'Body', level: 'beginner' },
  { english: 'brain', russian: 'мозг', kazakh: 'ми', category: 'Body', level: 'beginner' },
  { english: 'skin', russian: 'кожа', kazakh: 'тері', category: 'Body', level: 'beginner' },
  { english: 'bone', russian: 'кость', kazakh: 'сүйек', category: 'Body', level: 'beginner' },
  { english: 'blood', russian: 'кровь', kazakh: 'қан', category: 'Body', level: 'beginner' },
  { english: 'elbow', russian: 'локоть', kazakh: 'шынтақ', category: 'Body', level: 'beginner' },
  { english: 'wrist', russian: 'запястье', kazakh: 'білек', category: 'Body', level: 'beginner' },
  { english: 'ankle', russian: 'лодыжка', kazakh: 'өкше', category: 'Body', level: 'beginner' },

  // Clothes - Одежда (30 слов)
  { english: 'shirt', russian: 'рубашка', kazakh: 'жейде', category: 'Clothes', level: 'beginner' },
  { english: 'pants', russian: 'брюки', kazakh: 'шалбар', category: 'Clothes', level: 'beginner' },
  { english: 'dress', russian: 'платье', kazakh: 'көйлек', category: 'Clothes', level: 'beginner' },
  { english: 'skirt', russian: 'юбка', kazakh: 'белдемше', category: 'Clothes', level: 'beginner' },
  { english: 'shoes', russian: 'туфли', kazakh: 'аяқ киім', category: 'Clothes', level: 'beginner' },
  { english: 'socks', russian: 'носки', kazakh: 'шұлық', category: 'Clothes', level: 'beginner' },
  { english: 'hat', russian: 'шляпа', kazakh: 'қалпақ', category: 'Clothes', level: 'beginner' },
  { english: 'cap', russian: 'кепка', kazakh: 'бөрік', category: 'Clothes', level: 'beginner' },
  { english: 'coat', russian: 'пальто', kazakh: 'пальто', category: 'Clothes', level: 'beginner' },
  { english: 'jacket', russian: 'куртка', kazakh: 'күрте', category: 'Clothes', level: 'beginner' },
  { english: 'sweater', russian: 'свитер', kazakh: 'жемпір', category: 'Clothes', level: 'beginner' },
  { english: 't-shirt', russian: 'футболка', kazakh: 'футболка', category: 'Clothes', level: 'beginner' },
  { english: 'jeans', russian: 'джинсы', kazakh: 'джинсы', category: 'Clothes', level: 'beginner' },
  { english: 'shorts', russian: 'шорты', kazakh: 'шорты', category: 'Clothes', level: 'beginner' },
  { english: 'gloves', russian: 'перчатки', kazakh: 'қолғап', category: 'Clothes', level: 'beginner' },
  { english: 'scarf', russian: 'шарф', kazakh: 'шарф', category: 'Clothes', level: 'beginner' },
  { english: 'boots', russian: 'сапоги', kazakh: 'етік', category: 'Clothes', level: 'beginner' },
  { english: 'sandals', russian: 'сандалии', kazakh: 'сандалия', category: 'Clothes', level: 'beginner' },
  { english: 'slippers', russian: 'тапочки', kazakh: 'тәпішке', category: 'Clothes', level: 'beginner' },
  { english: 'belt', russian: 'ремень', kazakh: 'белбеу', category: 'Clothes', level: 'beginner' },
  { english: 'tie', russian: 'галстук', kazakh: 'галстук', category: 'Clothes', level: 'beginner' },
  { english: 'suit', russian: 'костюм', kazakh: 'костюм', category: 'Clothes', level: 'beginner' },
  { english: 'uniform', russian: 'форма', kazakh: 'форма', category: 'Clothes', level: 'beginner' },
  { english: 'underwear', russian: 'нижнее белье', kazakh: 'іш киім', category: 'Clothes', level: 'beginner' },
  { english: 'pajamas', russian: 'пижама', kazakh: 'жатын киім', category: 'Clothes', level: 'beginner' },
  { english: 'raincoat', russian: 'дождевик', kazakh: 'жаңбыр киім', category: 'Clothes', level: 'beginner' },
  { english: 'umbrella', russian: 'зонт', kazakh: 'қолшатыр', category: 'Clothes', level: 'beginner' },
  { english: 'glasses', russian: 'очки', kazakh: 'көзілдірік', category: 'Clothes', level: 'beginner' },
  { english: 'watch', russian: 'часы', kazakh: 'сағат', category: 'Clothes', level: 'beginner' },
  { english: 'jewelry', russian: 'украшения', kazakh: 'зергерлік бұйым', category: 'Clothes', level: 'beginner' },

  // Toys - Игрушки (20 слов)
  { english: 'ball', russian: 'мяч', kazakh: 'доп', category: 'Toys', level: 'beginner' },
  { english: 'doll', russian: 'кукла', kazakh: 'қуыршақ', category: 'Toys', level: 'beginner' },
  { english: 'toy', russian: 'игрушка', kazakh: 'ойыншық', category: 'Toys', level: 'beginner' },
  { english: 'car', russian: 'машинка', kazakh: 'машина', category: 'Toys', level: 'beginner' },
  { english: 'train', russian: 'поезд', kazakh: 'пойыз', category: 'Toys', level: 'beginner' },
  { english: 'plane', russian: 'самолет', kazakh: 'ұшақ', category: 'Toys', level: 'beginner' },
  { english: 'robot', russian: 'робот', kazakh: 'робот', category: 'Toys', level: 'beginner' },
  { english: 'puzzle', russian: 'пазл', kazakh: 'пазл', category: 'Toys', level: 'beginner' },
  { english: 'blocks', russian: 'кубики', kazakh: 'кубиктер', category: 'Toys', level: 'beginner' },
  { english: 'teddy bear', russian: 'плюшевый мишка', kazakh: 'аю ойыншық', category: 'Toys', level: 'beginner' },
  { english: 'kite', russian: 'воздушный змей', kazakh: 'елбезек', category: 'Toys', level: 'beginner' },
  { english: 'balloon', russian: 'воздушный шар', kazakh: 'доп', category: 'Toys', level: 'beginner' },
  { english: 'bicycle', russian: 'велосипед', kazakh: 'велосипед', category: 'Toys', level: 'beginner' },
  { english: 'scooter', russian: 'самокат', kazakh: 'самокат', category: 'Toys', level: 'beginner' },
  { english: 'swing', russian: 'качели', kazakh: 'тербел', category: 'Toys', level: 'beginner' },
  { english: 'slide', russian: 'горка', kazakh: 'сырғанақ', category: 'Toys', level: 'beginner' },
  { english: 'sandbox', russian: 'песочница', kazakh: 'құм орны', category: 'Toys', level: 'beginner' },
  { english: 'jump rope', russian: 'скакалка', kazakh: 'секіртпе', category: 'Toys', level: 'beginner' },
  { english: 'marbles', russian: 'шарики', kazakh: 'шариктер', category: 'Toys', level: 'beginner' },
  { english: 'yo-yo', russian: 'йо-йо', kazakh: 'йо-йо', category: 'Toys', level: 'beginner' },

  // Fruits - Фрукты (25 слов)
  { english: 'apple', russian: 'яблоко', kazakh: 'алма', category: 'Fruits', level: 'beginner' },
  { english: 'banana', russian: 'банан', kazakh: 'банан', category: 'Fruits', level: 'beginner' },
  { english: 'orange', russian: 'апельсин', kazakh: 'апельсин', category: 'Fruits', level: 'beginner' },
  { english: 'grape', russian: 'виноград', kazakh: 'жүзім', category: 'Fruits', level: 'beginner' },
  { english: 'strawberry', russian: 'клубника', kazakh: 'құлпынай', category: 'Fruits', level: 'beginner' },
  { english: 'watermelon', russian: 'арбуз', kazakh: 'қарбыз', category: 'Fruits', level: 'beginner' },
  { english: 'melon', russian: 'дыня', kazakh: 'қауын', category: 'Fruits', level: 'beginner' },
  { english: 'pear', russian: 'груша', kazakh: 'алмұрт', category: 'Fruits', level: 'beginner' },
  { english: 'peach', russian: 'персик', kazakh: 'шабдалы', category: 'Fruits', level: 'beginner' },
  { english: 'plum', russian: 'слива', kazakh: 'алхоры', category: 'Fruits', level: 'beginner' },
  { english: 'cherry', russian: 'вишня', kazakh: 'шие', category: 'Fruits', level: 'beginner' },
  { english: 'lemon', russian: 'лимон', kazakh: 'лимон', category: 'Fruits', level: 'beginner' },
  { english: 'lime', russian: 'лайм', kazakh: 'лайм', category: 'Fruits', level: 'beginner' },
  { english: 'kiwi', russian: 'киви', kazakh: 'киви', category: 'Fruits', level: 'beginner' },
  { english: 'mango', russian: 'манго', kazakh: 'манго', category: 'Fruits', level: 'beginner' },
  { english: 'pineapple', russian: 'ананас', kazakh: 'ананас', category: 'Fruits', level: 'beginner' },
  { english: 'coconut', russian: 'кокос', kazakh: 'кокос', category: 'Fruits', level: 'beginner' },
  { english: 'apricot', russian: 'абрикос', kazakh: 'өрік', category: 'Fruits', level: 'beginner' },
  { english: 'raspberry', russian: 'малина', kazakh: 'таңқурай', category: 'Fruits', level: 'beginner' },
  { english: 'blueberry', russian: 'черника', kazakh: 'қара жидек', category: 'Fruits', level: 'beginner' },
  { english: 'blackberry', russian: 'ежевика', kazakh: 'қара өрік', category: 'Fruits', level: 'beginner' },
  { english: 'pomegranate', russian: 'гранат', kazakh: 'анар', category: 'Fruits', level: 'beginner' },
  { english: 'avocado', russian: 'авокадо', kazakh: 'авокадо', category: 'Fruits', level: 'beginner' },
  { english: 'papaya', russian: 'папайя', kazakh: 'папайя', category: 'Fruits', level: 'beginner' },
  { english: 'fig', russian: 'инжир', kazakh: 'інжір', category: 'Fruits', level: 'beginner' },

  // Vegetables - Овощи (25 слов)
  { english: 'carrot', russian: 'морковь', kazakh: 'сәбіз', category: 'Vegetables', level: 'beginner' },
  { english: 'potato', russian: 'картофель', kazakh: 'картоп', category: 'Vegetables', level: 'beginner' },
  { english: 'tomato', russian: 'помидор', kazakh: 'қызанақ', category: 'Vegetables', level: 'beginner' },
  { english: 'cucumber', russian: 'огурец', kazakh: 'қияр', category: 'Vegetables', level: 'beginner' },
  { english: 'onion', russian: 'лук', kazakh: 'пияз', category: 'Vegetables', level: 'beginner' },
  { english: 'garlic', russian: 'чеснок', kazakh: 'сарымсақ', category: 'Vegetables', level: 'beginner' },
  { english: 'pepper', russian: 'перец', kazakh: 'бұрыш', category: 'Vegetables', level: 'beginner' },
  { english: 'cabbage', russian: 'капуста', kazakh: 'қырыққабат', category: 'Vegetables', level: 'beginner' },
  { english: 'lettuce', russian: 'салат', kazakh: 'салат', category: 'Vegetables', level: 'beginner' },
  { english: 'broccoli', russian: 'брокколи', kazakh: 'брокколи', category: 'Vegetables', level: 'beginner' },
  { english: 'cauliflower', russian: 'цветная капуста', kazakh: 'гүлді қырыққабат', category: 'Vegetables', level: 'beginner' },
  { english: 'pumpkin', russian: 'тыква', kazakh: 'асқабақ', category: 'Vegetables', level: 'beginner' },
  { english: 'eggplant', russian: 'баклажан', kazakh: 'бадамжан', category: 'Vegetables', level: 'beginner' },
  { english: 'zucchini', russian: 'кабачок', kazakh: 'кәді', category: 'Vegetables', level: 'beginner' },
  { english: 'corn', russian: 'кукуруза', kazakh: 'жүгері', category: 'Vegetables', level: 'beginner' },
  { english: 'peas', russian: 'горох', kazakh: 'бұршақ', category: 'Vegetables', level: 'beginner' },
  { english: 'beans', russian: 'фасоль', kazakh: 'бұршақ', category: 'Vegetables', level: 'beginner' },
  { english: 'spinach', russian: 'шпинат', kazakh: 'шпинат', category: 'Vegetables', level: 'beginner' },
  { english: 'celery', russian: 'сельдерей', kazakh: 'селдерей', category: 'Vegetables', level: 'beginner' },
  { english: 'beetroot', russian: 'свекла', kazakh: 'қызылша', category: 'Vegetables', level: 'beginner' },
  { english: 'radish', russian: 'редис', kazakh: 'редис', category: 'Vegetables', level: 'beginner' },
  { english: 'turnip', russian: 'репа', kazakh: 'шалғам', category: 'Vegetables', level: 'beginner' },
  { english: 'mushroom', russian: 'гриб', kazakh: 'саңырауқұлақ', category: 'Vegetables', level: 'beginner' },
  { english: 'asparagus', russian: 'спаржа', kazakh: 'спаржа', category: 'Vegetables', level: 'beginner' },
  { english: 'artichoke', russian: 'артишок', kazakh: 'артишок', category: 'Vegetables', level: 'beginner' },

  // Transport - Транспорт (20 слов)
  { english: 'car', russian: 'машина', kazakh: 'көлік', category: 'Transport', level: 'beginner' },
  { english: 'bus', russian: 'автобус', kazakh: 'автобус', category: 'Transport', level: 'beginner' },
  { english: 'train', russian: 'поезд', kazakh: 'пойыз', category: 'Transport', level: 'beginner' },
  { english: 'plane', russian: 'самолет', kazakh: 'ұшақ', category: 'Transport', level: 'beginner' },
  { english: 'ship', russian: 'корабль', kazakh: 'кеме', category: 'Transport', level: 'beginner' },
  { english: 'boat', russian: 'лодка', kazakh: 'қайық', category: 'Transport', level: 'beginner' },
  { english: 'bicycle', russian: 'велосипед', kazakh: 'велосипед', category: 'Transport', level: 'beginner' },
  { english: 'motorcycle', russian: 'мотоцикл', kazakh: 'мотоцикл', category: 'Transport', level: 'beginner' },
  { english: 'truck', russian: 'грузовик', kazakh: 'жүк көлік', category: 'Transport', level: 'beginner' },
  { english: 'taxi', russian: 'такси', kazakh: 'такси', category: 'Transport', level: 'beginner' },
  { english: 'helicopter', russian: 'вертолет', kazakh: 'тікұшақ', category: 'Transport', level: 'beginner' },
  { english: 'subway', russian: 'метро', kazakh: 'метро', category: 'Transport', level: 'beginner' },
  { english: 'tram', russian: 'трамвай', kazakh: 'трамвай', category: 'Transport', level: 'beginner' },
  { english: 'trolleybus', russian: 'троллейбус', kazakh: 'троллейбус', category: 'Transport', level: 'beginner' },
  { english: 'ambulance', russian: 'скорая помощь', kazakh: 'жедел жәрдем', category: 'Transport', level: 'beginner' },
  { english: 'fire truck', russian: 'пожарная машина', kazakh: 'өрт сөндіру', category: 'Transport', level: 'beginner' },
  { english: 'police car', russian: 'полицейская машина', kazakh: 'полиция көлігі', category: 'Transport', level: 'beginner' },
  { english: 'van', russian: 'фургон', kazakh: 'фургон', category: 'Transport', level: 'beginner' },
  { english: 'scooter', russian: 'самокат', kazakh: 'самокат', category: 'Transport', level: 'beginner' },
  { english: 'rocket', russian: 'ракета', kazakh: 'зымыран', category: 'Transport', level: 'beginner' },

  // ==================== ELEMENTARY (300+ слов) ====================
  
  // Food - Еда (40 слов)
  { english: 'bread', russian: 'хлеб', kazakh: 'нан', category: 'Food', level: 'elementary' },
  { english: 'milk', russian: 'молоко', kazakh: 'сүт', category: 'Food', level: 'elementary' },
  { english: 'water', russian: 'вода', kazakh: 'су', category: 'Food', level: 'elementary' },
  { english: 'juice', russian: 'сок', kazakh: 'шырын', category: 'Food', level: 'elementary' },
  { english: 'cheese', russian: 'сыр', kazakh: 'ірімшік', category: 'Food', level: 'elementary' },
  { english: 'egg', russian: 'яйцо', kazakh: 'жұмыртқа', category: 'Food', level: 'elementary' },
  { english: 'pizza', russian: 'пицца', kazakh: 'пицца', category: 'Food', level: 'elementary' },
  { english: 'cake', russian: 'торт', kazakh: 'торт', category: 'Food', level: 'elementary' },
  { english: 'cookie', russian: 'печенье', kazakh: 'печенье', category: 'Food', level: 'elementary' },
  { english: 'candy', russian: 'конфета', kazakh: 'кәмпит', category: 'Food', level: 'elementary' },
  { english: 'chocolate', russian: 'шоколад', kazakh: 'шоколад', category: 'Food', level: 'elementary' },
  { english: 'ice cream', russian: 'мороженое', kazakh: 'балмұздақ', category: 'Food', level: 'elementary' },
  { english: 'soup', russian: 'суп', kazakh: 'сорпа', category: 'Food', level: 'elementary' },
  { english: 'salad', russian: 'салат', kazakh: 'салат', category: 'Food', level: 'elementary' },
  { english: 'sandwich', russian: 'бутерброд', kazakh: 'бутерброд', category: 'Food', level: 'elementary' },
  { english: 'hamburger', russian: 'гамбургер', kazakh: 'гамбургер', category: 'Food', level: 'elementary' },
  { english: 'hot dog', russian: 'хот-дог', kazakh: 'хот-дог', category: 'Food', level: 'elementary' },
  { english: 'pasta', russian: 'макароны', kazakh: 'макарон', category: 'Food', level: 'elementary' },
  { english: 'rice', russian: 'рис', kazakh: 'күріш', category: 'Food', level: 'elementary' },
  { english: 'noodles', russian: 'лапша', kazakh: 'кеспе', category: 'Food', level: 'elementary' },
  { english: 'meat', russian: 'мясо', kazakh: 'ет', category: 'Food', level: 'elementary' },
  { english: 'chicken', russian: 'курица', kazakh: 'тауық', category: 'Food', level: 'elementary' },
  { english: 'beef', russian: 'говядина', kazakh: 'сиыр еті', category: 'Food', level: 'elementary' },
  { english: 'pork', russian: 'свинина', kazakh: 'шошқа еті', category: 'Food', level: 'elementary' },
  { english: 'fish', russian: 'рыба', kazakh: 'балық', category: 'Food', level: 'elementary' },
  { english: 'sausage', russian: 'колбаса', kazakh: 'шұжық', category: 'Food', level: 'elementary' },
  { english: 'bacon', russian: 'бекон', kazakh: 'бекон', category: 'Food', level: 'elementary' },
  { english: 'butter', russian: 'масло', kazakh: 'май', category: 'Food', level: 'elementary' },
  { english: 'oil', russian: 'масло', kazakh: 'май', category: 'Food', level: 'elementary' },
  { english: 'salt', russian: 'соль', kazakh: 'тұз', category: 'Food', level: 'elementary' },
  { english: 'sugar', russian: 'сахар', kazakh: 'қант', category: 'Food', level: 'elementary' },
  { english: 'pepper', russian: 'перец', kazakh: 'бұрыш', category: 'Food', level: 'elementary' },
  { english: 'sauce', russian: 'соус', kazakh: 'тұздық', category: 'Food', level: 'elementary' },
  { english: 'ketchup', russian: 'кетчуп', kazakh: 'кетчуп', category: 'Food', level: 'elementary' },
  { english: 'mustard', russian: 'горчица', kazakh: 'қыша', category: 'Food', level: 'elementary' },
  { english: 'mayonnaise', russian: 'майонез', kazakh: 'майонез', category: 'Food', level: 'elementary' },
  { english: 'yogurt', russian: 'йогурт', kazakh: 'йогурт', category: 'Food', level: 'elementary' },
  { english: 'cream', russian: 'сливки', kazakh: 'қаймақ', category: 'Food', level: 'elementary' },
  { english: 'honey', russian: 'мед', kazakh: 'бал', category: 'Food', level: 'elementary' },
  { english: 'jam', russian: 'варенье', kazakh: 'кілегей', category: 'Food', level: 'elementary' },

  // School - Школа (40 слов)
  { english: 'book', russian: 'книга', kazakh: 'кітап', category: 'School', level: 'elementary' },
  { english: 'pen', russian: 'ручка', kazakh: 'қалам', category: 'School', level: 'elementary' },
  { english: 'pencil', russian: 'карандаш', kazakh: 'қарындаш', category: 'School', level: 'elementary' },
  { english: 'desk', russian: 'парта', kazakh: 'парта', category: 'School', level: 'elementary' },
  { english: 'teacher', russian: 'учитель', kazakh: 'мұғалім', category: 'School', level: 'elementary' },
  { english: 'student', russian: 'ученик', kazakh: 'оқушы', category: 'School', level: 'elementary' },
  { english: 'classroom', russian: 'класс', kazakh: 'сынып', category: 'School', level: 'elementary' },
  { english: 'homework', russian: 'домашняя работа', kazakh: 'үй жұмысы', category: 'School', level: 'elementary' },
  { english: 'lesson', russian: 'урок', kazakh: 'сабақ', category: 'School', level: 'elementary' },
  { english: 'subject', russian: 'предмет', kazakh: 'пән', category: 'School', level: 'elementary' },
  { english: 'math', russian: 'математика', kazakh: 'математика', category: 'School', level: 'elementary' },
  { english: 'science', russian: 'наука', kazakh: 'ғылым', category: 'School', level: 'elementary' },
  { english: 'history', russian: 'история', kazakh: 'тарих', category: 'School', level: 'elementary' },
  { english: 'geography', russian: 'география', kazakh: 'география', category: 'School', level: 'elementary' },
  { english: 'art', russian: 'рисование', kazakh: 'сурет', category: 'School', level: 'elementary' },
  { english: 'music', russian: 'музыка', kazakh: 'музыка', category: 'School', level: 'elementary' },
  { english: 'sports', russian: 'физкультура', kazakh: 'дене шынықтыру', category: 'School', level: 'elementary' },
  { english: 'reading', russian: 'чтение', kazakh: 'оқу', category: 'School', level: 'elementary' },
  { english: 'writing', russian: 'письмо', kazakh: 'жазу', category: 'School', level: 'elementary' },
  { english: 'notebook', russian: 'тетрадь', kazakh: 'дәптер', category: 'School', level: 'elementary' },
  { english: 'eraser', russian: 'ластик', kazakh: 'өшіргіш', category: 'School', level: 'elementary' },
  { english: 'ruler', russian: 'линейка', kazakh: 'сызғыш', category: 'School', level: 'elementary' },
  { english: 'scissors', russian: 'ножницы', kazakh: 'қайшы', category: 'School', level: 'elementary' },
  { english: 'glue', russian: 'клей', kazakh: 'желім', category: 'School', level: 'elementary' },
  { english: 'paper', russian: 'бумага', kazakh: 'қағаз', category: 'School', level: 'elementary' },
  { english: 'backpack', russian: 'рюкзак', kazakh: 'рюкзак', category: 'School', level: 'elementary' },
  { english: 'lunch', russian: 'обед', kazakh: 'түскі ас', category: 'School', level: 'elementary' },
  { english: 'break', russian: 'перемена', kazakh: 'үзіліс', category: 'School', level: 'elementary' },
  { english: 'test', russian: 'тест', kazakh: 'тест', category: 'School', level: 'elementary' },
  { english: 'exam', russian: 'экзамен', kazakh: 'емтихан', category: 'School', level: 'elementary' },
  { english: 'grade', russian: 'оценка', kazakh: 'баға', category: 'School', level: 'elementary' },
  { english: 'library', russian: 'библиотека', kazakh: 'кітапхана', category: 'School', level: 'elementary' },
  { english: 'gym', russian: 'спортзал', kazakh: 'спорт залы', category: 'School', level: 'elementary' },
  { english: 'playground', russian: 'площадка', kazakh: 'ойын алаңы', category: 'School', level: 'elementary' },
  { english: 'principal', russian: 'директор', kazakh: 'директор', category: 'School', level: 'elementary' },
  { english: 'friend', russian: 'друг', kazakh: 'дос', category: 'School', level: 'elementary' },
  { english: 'classmate', russian: 'одноклассник', kazakh: 'сыныптас', category: 'School', level: 'elementary' },
  { english: 'board', russian: 'доска', kazakh: 'тақта', category: 'School', level: 'elementary' },
  { english: 'chalk', russian: 'мел', kazakh: 'бор', category: 'School', level: 'elementary' },
  { english: 'marker', russian: 'маркер', kazakh: 'маркер', category: 'School', level: 'elementary' },

  // Home - Дом (40 слов)
  { english: 'house', russian: 'дом', kazakh: 'үй', category: 'Home', level: 'elementary' },
  { english: 'room', russian: 'комната', kazakh: 'бөлме', category: 'Home', level: 'elementary' },
  { english: 'door', russian: 'дверь', kazakh: 'есік', category: 'Home', level: 'elementary' },
  { english: 'window', russian: 'окно', kazakh: 'терезе', category: 'Home', level: 'elementary' },
  { english: 'bed', russian: 'кровать', kazakh: 'төсек', category: 'Home', level: 'elementary' },
  { english: 'table', russian: 'стол', kazakh: 'үстел', category: 'Home', level: 'elementary' },
  { english: 'chair', russian: 'стул', kazakh: 'орындық', category: 'Home', level: 'elementary' },
  { english: 'kitchen', russian: 'кухня', kazakh: 'ас үй', category: 'Home', level: 'elementary' },
  { english: 'bedroom', russian: 'спальня', kazakh: 'жатын бөлме', category: 'Home', level: 'elementary' },
  { english: 'bathroom', russian: 'ванная', kazakh: 'жуынатын бөлме', category: 'Home', level: 'elementary' },
  { english: 'living room', russian: 'гостиная', kazakh: 'қонақ бөлме', category: 'Home', level: 'elementary' },
  { english: 'toilet', russian: 'туалет', kazakh: 'әжетхана', category: 'Home', level: 'elementary' },
  { english: 'shower', russian: 'душ', kazakh: 'душ', category: 'Home', level: 'elementary' },
  { english: 'bathtub', russian: 'ванна', kazakh: 'ванна', category: 'Home', level: 'elementary' },
  { english: 'sink', russian: 'раковина', kazakh: 'раковина', category: 'Home', level: 'elementary' },
  { english: 'mirror', russian: 'зеркало', kazakh: 'айна', category: 'Home', level: 'elementary' },
  { english: 'refrigerator', russian: 'холодильник', kazakh: 'тоңазытқыш', category: 'Home', level: 'elementary' },
  { english: 'stove', russian: 'плита', kazakh: 'плита', category: 'Home', level: 'elementary' },
  { english: 'oven', russian: 'духовка', kazakh: 'пеш', category: 'Home', level: 'elementary' },
  { english: 'microwave', russian: 'микроволновка', kazakh: 'микротолқынды пеш', category: 'Home', level: 'elementary' },
  { english: 'dishwasher', russian: 'посудомойка', kazakh: 'ыдыс жуу машинасы', category: 'Home', level: 'elementary' },
  { english: 'washing machine', russian: 'стиральная машина', kazakh: 'кір жуу машинасы', category: 'Home', level: 'elementary' },
  { english: 'television', russian: 'телевизор', kazakh: 'теледидар', category: 'Home', level: 'elementary' },
  { english: 'computer', russian: 'компьютер', kazakh: 'компьютер', category: 'Home', level: 'elementary' },
  { english: 'phone', russian: 'телефон', kazakh: 'телефон', category: 'Home', level: 'elementary' },
  { english: 'sofa', russian: 'диван', kazakh: 'диван', category: 'Home', level: 'elementary' },
  { english: 'armchair', russian: 'кресло', kazakh: 'креслo', category: 'Home', level: 'elementary' },
  { english: 'carpet', russian: 'ковер', kazakh: 'кілем', category: 'Home', level: 'elementary' },
  { english: 'curtain', russian: 'штора', kazakh: 'перде', category: 'Home', level: 'elementary' },
  { english: 'pillow', russian: 'подушка', kazakh: 'жастық', category: 'Home', level: 'elementary' },
  { english: 'blanket', russian: 'одеяло', kazakh: 'көрпе', category: 'Home', level: 'elementary' },
  { english: 'sheet', russian: 'простыня', kazakh: 'төсек жапқыш', category: 'Home', level: 'elementary' },
  { english: 'lamp', russian: 'лампа', kazakh: 'шам', category: 'Home', level: 'elementary' },
  { english: 'clock', russian: 'часы', kazakh: 'сағат', category: 'Home', level: 'elementary' },
  { english: 'picture', russian: 'картина', kazakh: 'сурет', category: 'Home', level: 'elementary' },
  { english: 'shelf', russian: 'полка', kazakh: 'сөре', category: 'Home', level: 'elementary' },
  { english: 'closet', russian: 'шкаф', kazakh: 'шкаф', category: 'Home', level: 'elementary' },
  { english: 'drawer', russian: 'ящик', kazakh: 'тартпа', category: 'Home', level: 'elementary' },
  { english: 'stairs', russian: 'лестница', kazakh: 'баспалдақ', category: 'Home', level: 'elementary' },
  { english: 'garage', russian: 'гараж', kazakh: 'гараж', category: 'Home', level: 'elementary' },

  // Weather - Погода (25 слов)
  { english: 'weather', russian: 'погода', kazakh: 'ауа райы', category: 'Weather', level: 'elementary' },
  { english: 'sun', russian: 'солнце', kazakh: 'күн', category: 'Weather', level: 'elementary' },
  { english: 'rain', russian: 'дождь', kazakh: 'жаңбыр', category: 'Weather', level: 'elementary' },
  { english: 'snow', russian: 'снег', kazakh: 'қар', category: 'Weather', level: 'elementary' },
  { english: 'wind', russian: 'ветер', kazakh: 'жел', category: 'Weather', level: 'elementary' },
  { english: 'cloud', russian: 'облако', kazakh: 'бұлт', category: 'Weather', level: 'elementary' },
  { english: 'storm', russian: 'буря', kazakh: 'дауыл', category: 'Weather', level: 'elementary' },
  { english: 'thunder', russian: 'гром', kazakh: 'күн күркіреу', category: 'Weather', level: 'elementary' },
  { english: 'lightning', russian: 'молния', kazakh: 'найзағай', category: 'Weather', level: 'elementary' },
  { english: 'fog', russian: 'туман', kazakh: 'тұман', category: 'Weather', level: 'elementary' },
  { english: 'rainbow', russian: 'радуга', kazakh: 'кемпірқосақ', category: 'Weather', level: 'elementary' },
  { english: 'hot', russian: 'жарко', kazakh: 'ыстық', category: 'Weather', level: 'elementary' },
  { english: 'cold', russian: 'холодно', kazakh: 'суық', category: 'Weather', level: 'elementary' },
  { english: 'warm', russian: 'тепло', kazakh: 'жылы', category: 'Weather', level: 'elementary' },
  { english: 'cool', russian: 'прохладно', kazakh: 'салқын', category: 'Weather', level: 'elementary' },
  { english: 'sunny', russian: 'солнечно', kazakh: 'ашық', category: 'Weather', level: 'elementary' },
  { english: 'cloudy', russian: 'облачно', kazakh: 'бұлтты', category: 'Weather', level: 'elementary' },
  { english: 'rainy', russian: 'дождливо', kazakh: 'жаңбырлы', category: 'Weather', level: 'elementary' },
  { english: 'snowy', russian: 'снежно', kazakh: 'қарлы', category: 'Weather', level: 'elementary' },
  { english: 'windy', russian: 'ветрено', kazakh: 'желді', category: 'Weather', level: 'elementary' },
  { english: 'humid', russian: 'влажно', kazakh: 'ылғалды', category: 'Weather', level: 'elementary' },
  { english: 'dry', russian: 'сухо', kazakh: 'құрғақ', category: 'Weather', level: 'elementary' },
  { english: 'temperature', russian: 'температура', kazakh: 'температура', category: 'Weather', level: 'elementary' },
  { english: 'forecast', russian: 'прогноз', kazakh: 'болжам', category: 'Weather', level: 'elementary' },
  { english: 'season', russian: 'сезон', kazakh: 'маусым', category: 'Weather', level: 'elementary' },

  // Sports - Спорт (30 слов)
  { english: 'football', russian: 'футбол', kazakh: 'футбол', category: 'Sports', level: 'elementary' },
  { english: 'basketball', russian: 'баскетбол', kazakh: 'баскетбол', category: 'Sports', level: 'elementary' },
  { english: 'volleyball', russian: 'волейбол', kazakh: 'волейбол', category: 'Sports', level: 'elementary' },
  { english: 'tennis', russian: 'теннис', kazakh: 'теннис', category: 'Sports', level: 'elementary' },
  { english: 'hockey', russian: 'хоккей', kazakh: 'хоккей', category: 'Sports', level: 'elementary' },
  { english: 'baseball', russian: 'бейсбол', kazakh: 'бейсбол', category: 'Sports', level: 'elementary' },
  { english: 'swimming', russian: 'плавание', kazakh: 'жүзу', category: 'Sports', level: 'elementary' },
  { english: 'running', russian: 'бег', kazakh: 'жүгіру', category: 'Sports', level: 'elementary' },
  { english: 'skiing', russian: 'лыжный спорт', kazakh: 'шаңғы', category: 'Sports', level: 'elementary' },
  { english: 'skating', russian: 'катание', kazakh: 'сырғанау', category: 'Sports', level: 'elementary' },
  { english: 'boxing', russian: 'бокс', kazakh: 'бокс', category: 'Sports', level: 'elementary' },
  { english: 'wrestling', russian: 'борьба', kazakh: 'күрес', category: 'Sports', level: 'elementary' },
  { english: 'gymnastics', russian: 'гимнастика', kazakh: 'гимнастика', category: 'Sports', level: 'elementary' },
  { english: 'cycling', russian: 'велоспорт', kazakh: 'велоспорт', category: 'Sports', level: 'elementary' },
  { english: 'golf', russian: 'гольф', kazakh: 'гольф', category: 'Sports', level: 'elementary' },
  { english: 'badminton', russian: 'бадминтон', kazakh: 'бадминтон', category: 'Sports', level: 'elementary' },
  { english: 'table tennis', russian: 'настольный теннис', kazakh: 'үстел теннисі', category: 'Sports', level: 'elementary' },
  { english: 'chess', russian: 'шахматы', kazakh: 'шахмат', category: 'Sports', level: 'elementary' },
  { english: 'judo', russian: 'дзюдо', kazakh: 'дзюдо', category: 'Sports', level: 'elementary' },
  { english: 'karate', russian: 'карате', kazakh: 'карате', category: 'Sports', level: 'elementary' },
  { english: 'yoga', russian: 'йога', kazakh: 'йога', category: 'Sports', level: 'elementary' },
  { english: 'fitness', russian: 'фитнес', kazakh: 'фитнес', category: 'Sports', level: 'elementary' },
  { english: 'athlete', russian: 'спортсмен', kazakh: 'спортшы', category: 'Sports', level: 'elementary' },
  { english: 'coach', russian: 'тренер', kazakh: 'жаттықтырушы', category: 'Sports', level: 'elementary' },
  { english: 'team', russian: 'команда', kazakh: 'команда', category: 'Sports', level: 'elementary' },
  { english: 'game', russian: 'игра', kazakh: 'ойын', category: 'Sports', level: 'elementary' },
  { english: 'match', russian: 'матч', kazakh: 'матч', category: 'Sports', level: 'elementary' },
  { english: 'stadium', russian: 'стадион', kazakh: 'стадион', category: 'Sports', level: 'elementary' },
  { english: 'medal', russian: 'медаль', kazakh: 'медаль', category: 'Sports', level: 'elementary' },
  { english: 'trophy', russian: 'трофей', kazakh: 'кубок', category: 'Sports', level: 'elementary' },

  // Professions - Профессии (30 слов)
  { english: 'doctor', russian: 'врач', kazakh: 'дәрігер', category: 'Professions', level: 'elementary' },
  { english: 'teacher', russian: 'учитель', kazakh: 'мұғалім', category: 'Professions', level: 'elementary' },
  { english: 'engineer', russian: 'инженер', kazakh: 'инженер', category: 'Professions', level: 'elementary' },
  { english: 'nurse', russian: 'медсестра', kazakh: 'мейірбике', category: 'Professions', level: 'elementary' },
  { english: 'police officer', russian: 'полицейский', kazakh: 'полицей', category: 'Professions', level: 'elementary' },
  { english: 'firefighter', russian: 'пожарный', kazakh: 'өрт сөндіруші', category: 'Professions', level: 'elementary' },
  { english: 'pilot', russian: 'пилот', kazakh: 'ұшқыш', category: 'Professions', level: 'elementary' },
  { english: 'driver', russian: 'водитель', kazakh: 'жүргізуші', category: 'Professions', level: 'elementary' },
  { english: 'chef', russian: 'повар', kazakh: 'аспаз', category: 'Professions', level: 'elementary' },
  { english: 'waiter', russian: 'официант', kazakh: 'даяшы', category: 'Professions', level: 'elementary' },
  { english: 'singer', russian: 'певец', kazakh: 'әнші', category: 'Professions', level: 'elementary' },
  { english: 'actor', russian: 'актер', kazakh: 'актер', category: 'Professions', level: 'elementary' },
  { english: 'dancer', russian: 'танцор', kazakh: 'би билеуші', category: 'Professions', level: 'elementary' },
  { english: 'artist', russian: 'художник', kazakh: 'суретші', category: 'Professions', level: 'elementary' },
  { english: 'musician', russian: 'музыкант', kazakh: 'музыкант', category: 'Professions', level: 'elementary' },
  { english: 'writer', russian: 'писатель', kazakh: 'жазушы', category: 'Professions', level: 'elementary' },
  { english: 'journalist', russian: 'журналист', kazakh: 'журналист', category: 'Professions', level: 'elementary' },
  { english: 'photographer', russian: 'фотограф', kazakh: 'фотограф', category: 'Professions', level: 'elementary' },
  { english: 'scientist', russian: 'ученый', kazakh: 'ғалым', category: 'Professions', level: 'elementary' },
  { english: 'lawyer', russian: 'юрист', kazakh: 'заңгер', category: 'Professions', level: 'elementary' },
  { english: 'dentist', russian: 'стоматолог', kazakh: 'тіс дәрігері', category: 'Professions', level: 'elementary' },
  { english: 'veterinarian', russian: 'ветеринар', kazakh: 'ветеринар', category: 'Professions', level: 'elementary' },
  { english: 'farmer', russian: 'фермер', kazakh: 'фермер', category: 'Professions', level: 'elementary' },
  { english: 'builder', russian: 'строитель', kazakh: 'құрылысшы', category: 'Professions', level: 'elementary' },
  { english: 'electrician', russian: 'электрик', kazakh: 'электрик', category: 'Professions', level: 'elementary' },
  { english: 'plumber', russian: 'сантехник', kazakh: 'сантехник', category: 'Professions', level: 'elementary' },
  { english: 'mechanic', russian: 'механик', kazakh: 'механик', category: 'Professions', level: 'elementary' },
  { english: 'barber', russian: 'парикмахер', kazakh: 'шаштараз', category: 'Professions', level: 'elementary' },
  { english: 'soldier', russian: 'солдат', kazakh: 'сарбаз', category: 'Professions', level: 'elementary' },
  { english: 'astronaut', russian: 'космонавт', kazakh: 'ғарышкер', category: 'Professions', level: 'elementary' },

  // Days & Time - Дни и время (30 слов)
  { english: 'Monday', russian: 'понедельник', kazakh: 'дүйсенбі', category: 'Time', level: 'elementary' },
  { english: 'Tuesday', russian: 'вторник', kazakh: 'сейсенбі', category: 'Time', level: 'elementary' },
  { english: 'Wednesday', russian: 'среда', kazakh: 'сәрсенбі', category: 'Time', level: 'elementary' },
  { english: 'Thursday', russian: 'четверг', kazakh: 'бейсенбі', category: 'Time', level: 'elementary' },
  { english: 'Friday', russian: 'пятница', kazakh: 'жұма', category: 'Time', level: 'elementary' },
  { english: 'Saturday', russian: 'суббота', kazakh: 'сенбі', category: 'Time', level: 'elementary' },
  { english: 'Sunday', russian: 'воскресенье', kazakh: 'жексенбі', category: 'Time', level: 'elementary' },
  { english: 'January', russian: 'январь', kazakh: 'қаңтар', category: 'Time', level: 'elementary' },
  { english: 'February', russian: 'февраль', kazakh: 'ақпан', category: 'Time', level: 'elementary' },
  { english: 'March', russian: 'март', kazakh: 'наурыз', category: 'Time', level: 'elementary' },
  { english: 'April', russian: 'апрель', kazakh: 'сәуір', category: 'Time', level: 'elementary' },
  { english: 'May', russian: 'май', kazakh: 'мамыр', category: 'Time', level: 'elementary' },
  { english: 'June', russian: 'июнь', kazakh: 'маусым', category: 'Time', level: 'elementary' },
  { english: 'July', russian: 'июль', kazakh: 'шілде', category: 'Time', level: 'elementary' },
  { english: 'August', russian: 'август', kazakh: 'тамыз', category: 'Time', level: 'elementary' },
  { english: 'September', russian: 'сентябрь', kazakh: 'қыркүйек', category: 'Time', level: 'elementary' },
  { english: 'October', russian: 'октябрь', kazakh: 'қазан', category: 'Time', level: 'elementary' },
  { english: 'November', russian: 'ноябрь', kazakh: 'қараша', category: 'Time', level: 'elementary' },
  { english: 'December', russian: 'декабрь', kazakh: 'желтоқсан', category: 'Time', level: 'elementary' },
  { english: 'morning', russian: 'утро', kazakh: 'таң', category: 'Time', level: 'elementary' },
  { english: 'afternoon', russian: 'день', kazakh: 'күндіз', category: 'Time', level: 'elementary' },
  { english: 'evening', russian: 'вечер', kazakh: 'кеш', category: 'Time', level: 'elementary' },
  { english: 'night', russian: 'ночь', kazakh: 'түн', category: 'Time', level: 'elementary' },
  { english: 'today', russian: 'сегодня', kazakh: 'бүгін', category: 'Time', level: 'elementary' },
  { english: 'yesterday', russian: 'вчера', kazakh: 'кеше', category: 'Time', level: 'elementary' },
  { english: 'tomorrow', russian: 'завтра', kazakh: 'ертең', category: 'Time', level: 'elementary' },
  { english: 'week', russian: 'неделя', kazakh: 'апта', category: 'Time', level: 'elementary' },
  { english: 'month', russian: 'месяц', kazakh: 'ай', category: 'Time', level: 'elementary' },
  { english: 'year', russian: 'год', kazakh: 'жыл', category: 'Time', level: 'elementary' },
  { english: 'hour', russian: 'час', kazakh: 'сағат', category: 'Time', level: 'elementary' },

  // Places - Места (30 слов)
  { english: 'school', russian: 'школа', kazakh: 'мектеп', category: 'Places', level: 'elementary' },
  { english: 'hospital', russian: 'больница', kazakh: 'ауруха��а', category: 'Places', level: 'elementary' },
  { english: 'shop', russian: 'магазин', kazakh: 'дүкен', category: 'Places', level: 'elementary' },
  { english: 'restaurant', russian: 'ресторан', kazakh: 'мейрамхана', category: 'Places', level: 'elementary' },
  { english: 'cafe', russian: 'кафе', kazakh: 'кафе', category: 'Places', level: 'elementary' },
  { english: 'bank', russian: 'банк', kazakh: 'банк', category: 'Places', level: 'elementary' },
  { english: 'post office', russian: 'почта', kazakh: 'пошта', category: 'Places', level: 'elementary' },
  { english: 'airport', russian: 'аэропорт', kazakh: 'әуежай', category: 'Places', level: 'elementary' },
  { english: 'station', russian: 'вокзал', kazakh: 'вокзал', category: 'Places', level: 'elementary' },
  { english: 'park', russian: 'парк', kazakh: 'саябақ', category: 'Places', level: 'elementary' },
  { english: 'zoo', russian: 'зоопарк', kazakh: 'хайуанаттар бағы', category: 'Places', level: 'elementary' },
  { english: 'museum', russian: 'музей', kazakh: 'мұражай', category: 'Places', level: 'elementary' },
  { english: 'cinema', russian: 'кинотеатр', kazakh: 'кинотеатр', category: 'Places', level: 'elementary' },
  { english: 'theater', russian: 'театр', kazakh: 'театр', category: 'Places', level: 'elementary' },
  { english: 'library', russian: 'библиотека', kazakh: 'кітапхана', category: 'Places', level: 'elementary' },
  { english: 'church', russian: 'церковь', kazakh: 'шіркеу', category: 'Places', level: 'elementary' },
  { english: 'mosque', russian: 'мечеть', kazakh: 'мешіт', category: 'Places', level: 'elementary' },
  { english: 'beach', russian: 'пляж', kazakh: 'жағажай', category: 'Places', level: 'elementary' },
  { english: 'mountain', russian: 'гора', kazakh: 'тау', category: 'Places', level: 'elementary' },
  { english: 'river', russian: 'река', kazakh: 'өзен', category: 'Places', level: 'elementary' },
  { english: 'lake', russian: 'озеро', kazakh: 'көл', category: 'Places', level: 'elementary' },
  { english: 'forest', russian: 'лес', kazakh: 'орман', category: 'Places', level: 'elementary' },
  { english: 'bridge', russian: 'мост', kazakh: 'көпір', category: 'Places', level: 'elementary' },
  { english: 'road', russian: 'дорога', kazakh: 'жол', category: 'Places', level: 'elementary' },
  { english: 'street', russian: 'улица', kazakh: 'көше', category: 'Places', level: 'elementary' },
  { english: 'square', russian: 'площадь', kazakh: 'алаң', category: 'Places', level: 'elementary' },
  { english: 'market', russian: 'рынок', kazakh: 'базар', category: 'Places', level: 'elementary' },
  { english: 'pharmacy', russian: 'аптека', kazakh: 'дәріхана', category: 'Places', level: 'elementary' },
  { english: 'hotel', russian: 'отель', kazakh: 'қонақүй', category: 'Places', level: 'elementary' },
  { english: 'factory', russian: 'фабрика', kazakh: 'зауыт', category: 'Places', level: 'elementary' },

  // Emotions - Эмоции (25 слов)
  { english: 'happy', russian: 'счастливый', kazakh: 'бақытты', category: 'Emotions', level: 'elementary' },
  { english: 'sad', russian: 'грустный', kazakh: 'қайғылы', category: 'Emotions', level: 'elementary' },
  { english: 'angry', russian: 'злой', kazakh: 'ашулы', category: 'Emotions', level: 'elementary' },
  { english: 'scared', russian: 'испуганный', kazakh: 'қорыққан', category: 'Emotions', level: 'elementary' },
  { english: 'tired', russian: 'уставший', kazakh: 'шаршаған', category: 'Emotions', level: 'elementary' },
  { english: 'excited', russian: 'взволнованный', kazakh: 'толқыған', category: 'Emotions', level: 'elementary' },
  { english: 'bored', russian: 'скучный', kazakh: 'зерігіп қалған', category: 'Emotions', level: 'elementary' },
  { english: 'surprised', russian: 'удивленный', kazakh: 'таңғалған', category: 'Emotions', level: 'elementary' },
  { english: 'nervous', russian: 'нервный', kazakh: 'мазасыз', category: 'Emotions', level: 'elementary' },
  { english: 'calm', russian: 'спокойный', kazakh: 'тыныш', category: 'Emotions', level: 'elementary' },
  { english: 'proud', russian: 'гордый', kazakh: 'мақтан', category: 'Emotions', level: 'elementary' },
  { english: 'shy', russian: 'застенчивый', kazakh: 'ұялшақ', category: 'Emotions', level: 'elementary' },
  { english: 'lonely', russian: 'одинокий', kazakh: 'жалғыз', category: 'Emotions', level: 'elementary' },
  { english: 'brave', russian: 'смелый', kazakh: 'батыл', category: 'Emotions', level: 'elementary' },
  { english: 'worried', russian: 'обеспокоенный', kazakh: 'алаңдаған', category: 'Emotions', level: 'elementary' },
  { english: 'confused', russian: 'смущенный', kazakh: 'шатасқан', category: 'Emotions', level: 'elementary' },
  { english: 'jealous', russian: 'ревнивый', kazakh: 'қызғаншақ', category: 'Emotions', level: 'elementary' },
  { english: 'silly', russian: 'глупый', kazakh: 'ақымақ', category: 'Emotions', level: 'elementary' },
  { english: 'curious', russian: 'любопытный', kazakh: 'қызықсынған', category: 'Emotions', level: 'elementary' },
  { english: 'friendly', russian: 'дружелюбный', kazakh: 'достық', category: 'Emotions', level: 'elementary' },
  { english: 'kind', russian: 'добрый', kazakh: 'мейірімді', category: 'Emotions', level: 'elementary' },
  { english: 'polite', russian: 'вежливый', kazakh: 'сыпайы', category: 'Emotions', level: 'elementary' },
  { english: 'rude', russian: 'грубый', kazakh: 'дөрекі', category: 'Emotions', level: 'elementary' },
  { english: 'funny', russian: 'смешной', kazakh: 'күлкілі', category: 'Emotions', level: 'elementary' },
  { english: 'serious', russian: 'серьезный', kazakh: 'байсалды', category: 'Emotions', level: 'elementary' },

  // (Добавим дополнительно 10 слов до 300)
  { english: 'spring', russian: 'весна', kazakh: 'көктем', category: 'Seasons', level: 'elementary' },
  { english: 'summer', russian: 'лето', kazakh: 'жаз', category: 'Seasons', level: 'elementary' },
  { english: 'autumn', russian: 'осень', kazakh: 'күз', category: 'Seasons', level: 'elementary' },
  { english: 'winter', russian: 'зима', kazakh: 'қыс', category: 'Seasons', level: 'elementary' },
  { english: 'birthday', russian: 'день рождения', kazakh: 'туған күн', category: 'Celebrations', level: 'elementary' },
  { english: 'holiday', russian: 'праздник', kazakh: 'мереке', category: 'Celebrations', level: 'elementary' },
  { english: 'party', russian: 'вечеринка', kazakh: 'той', category: 'Celebrations', level: 'elementary' },
  { english: 'gift', russian: 'подарок', kazakh: 'сыйлық', category: 'Celebrations', level: 'elementary' },
  { english: 'music', russian: 'музыка', kazakh: 'музыка', category: 'Entertainment', level: 'elementary' },
  { english: 'song', russian: 'песня', kazakh: 'ән', category: 'Entertainment', level: 'elementary' },

  // ==================== PRE-INTERMEDIATE (300+ слов) ====================
  
  // Nature - Природа (40 слов)
  { english: 'tree', russian: 'дерево', kazakh: 'ағаш', category: 'Nature', level: 'pre-intermediate' },
  { english: 'flower', russian: 'цветок', kazakh: 'гүл', category: 'Nature', level: 'pre-intermediate' },
  { english: 'grass', russian: 'трава', kazakh: 'шөп', category: 'Nature', level: 'pre-intermediate' },
  { english: 'leaf', russian: 'лист', kazakh: 'жапырақ', category: 'Nature', level: 'pre-intermediate' },
  { english: 'branch', russian: 'ветка', kazakh: 'бұтақ', category: 'Nature', level: 'pre-intermediate' },
  { english: 'root', russian: 'корень', kazakh: 'тамыр', category: 'Nature', level: 'pre-intermediate' },
  { english: 'seed', russian: 'семя', kazakh: 'тұқым', category: 'Nature', level: 'pre-intermediate' },
  { english: 'plant', russian: 'растение', kazakh: 'өсімдік', category: 'Nature', level: 'pre-intermediate' },
  { english: 'bush', russian: 'куст', kazakh: 'бұта', category: 'Nature', level: 'pre-intermediate' },
  { english: 'garden', russian: 'сад', kazakh: 'бақша', category: 'Nature', level: 'pre-intermediate' },
  { english: 'field', russian: 'поле', kazakh: 'дала', category: 'Nature', level: 'pre-intermediate' },
  { english: 'meadow', russian: 'луг', kazakh: 'шалғын', category: 'Nature', level: 'pre-intermediate' },
  { english: 'hill', russian: 'холм', kazakh: 'төбе', category: 'Nature', level: 'pre-intermediate' },
  { english: 'valley', russian: 'долина', kazakh: 'аңғар', category: 'Nature', level: 'pre-intermediate' },
  { english: 'waterfall', russian: 'водопад', kazakh: 'сарқырама', category: 'Nature', level: 'pre-intermediate' },
  { english: 'ocean', russian: 'океан', kazakh: 'мұхит', category: 'Nature', level: 'pre-intermediate' },
  { english: 'sea', russian: 'море', kazakh: 'теңіз', category: 'Nature', level: 'pre-intermediate' },
  { english: 'island', russian: 'остров', kazakh: 'арал', category: 'Nature', level: 'pre-intermediate' },
  { english: 'desert', russian: 'пустыня', kazakh: 'шөл', category: 'Nature', level: 'pre-intermediate' },
  { english: 'jungle', russian: 'джунгли', kazakh: 'джунгли', category: 'Nature', level: 'pre-intermediate' },
  { english: 'cave', russian: 'пещера', kazakh: 'үңгір', category: 'Nature', level: 'pre-intermediate' },
  { english: 'rock', russian: 'скала', kazakh: 'жартас', category: 'Nature', level: 'pre-intermediate' },
  { english: 'stone', russian: 'камень', kazakh: 'тас', category: 'Nature', level: 'pre-intermediate' },
  { english: 'sand', russian: 'песок', kazakh: 'құм', category: 'Nature', level: 'pre-intermediate' },
  { english: 'mud', russian: 'грязь', kazakh: 'балшық', category: 'Nature', level: 'pre-intermediate' },
  { english: 'soil', russian: 'почва', kazakh: 'топырақ', category: 'Nature', level: 'pre-intermediate' },
  { english: 'volcano', russian: 'вулкан', kazakh: 'жанартау', category: 'Nature', level: 'pre-intermediate' },
  { english: 'earthquake', russian: 'землетрясение', kazakh: 'жер сілкіну', category: 'Nature', level: 'pre-intermediate' },
  { english: 'planet', russian: 'планета', kazakh: 'ғаламшар', category: 'Nature', level: 'pre-intermediate' },
  { english: 'sky', russian: 'небо', kazakh: 'аспан', category: 'Nature', level: 'pre-intermediate' },
  { english: 'space', russian: 'космос', kazakh: 'ғарыш', category: 'Nature', level: 'pre-intermediate' },
  { english: 'air', russian: 'воздух', kazakh: 'ауа', category: 'Nature', level: 'pre-intermediate' },
  { english: 'oxygen', russian: 'кислород', kazakh: 'оттегі', category: 'Nature', level: 'pre-intermediate' },
  { english: 'atmosphere', russian: 'атмосфера', kazakh: 'атмосфера', category: 'Nature', level: 'pre-intermediate' },
  { english: 'environment', russian: 'окружающая среда', kazakh: 'қоршаған орта', category: 'Nature', level: 'pre-intermediate' },
  { english: 'nature', russian: 'природа', kazakh: 'табиғат', category: 'Nature', level: 'pre-intermediate' },
  { english: 'wildlife', russian: 'дикая природа', kazakh: 'жабайы табиғат', category: 'Nature', level: 'pre-intermediate' },
  { english: 'habitat', russian: 'среда обитания', kazakh: 'мекен орны', category: 'Nature', level: 'pre-intermediate' },
  { english: 'ecosystem', russian: 'экосистема', kazakh: 'экожүйе', category: 'Nature', level: 'pre-intermediate' },
  { english: 'climate', russian: 'климат', kazakh: 'климат', category: 'Nature', level: 'pre-intermediate' },
];

// Из-за ограничений по длине, продолжим в следующем файле
