// Продолжение расширенной базы данных - часть 2
import { Word } from './english-vocabulary-extended';

export const VOCABULARY_EXTENDED_PART2: Word[] = [
  // ==================== PRE-INTERMEDIATE продолжение ====================
  
  // Actions - Действия (40 слов)
  { english: 'run', russian: 'бегать', kazakh: 'жүгіру', category: 'Actions', level: 'pre-intermediate' },
  { english: 'jump', russian: 'прыгать', kazakh: 'секіру', category: 'Actions', level: 'pre-intermediate' },
  { english: 'swim', russian: 'плавать', kazakh: 'жүзу', category: 'Actions', level: 'pre-intermediate' },
  { english: 'read', russian: 'читать', kazakh: 'оқу', category: 'Actions', level: 'pre-intermediate' },
  { english: 'write', russian: 'писать', kazakh: 'жазу', category: 'Actions', level: 'pre-intermediate' },
  { english: 'draw', russian: 'рисовать', kazakh: 'сурет салу', category: 'Actions', level: 'pre-intermediate' },
  { english: 'sing', russian: 'петь', kazakh: 'ән айту', category: 'Actions', level: 'pre-intermediate' },
  { english: 'dance', russian: 'танцевать', kazakh: 'би билеу', category: 'Actions', level: 'pre-intermediate' },
  { english: 'walk', russian: 'ходить', kazakh: 'жүру', category: 'Actions', level: 'pre-intermediate' },
  { english: 'talk', russian: 'говорить', kazakh: 'сөйлеу', category: 'Actions', level: 'pre-intermediate' },
  { english: 'listen', russian: 'слушать', kazakh: 'тыңдау', category: 'Actions', level: 'pre-intermediate' },
  { english: 'watch', russian: 'смотреть', kazakh: 'қарау', category: 'Actions', level: 'pre-intermediate' },
  { english: 'see', russian: 'видеть', kazakh: 'көру', category: 'Actions', level: 'pre-intermediate' },
  { english: 'hear', russian: 'слышать', kazakh: 'есту', category: 'Actions', level: 'pre-intermediate' },
  { english: 'smell', russian: 'нюхать', kazakh: 'иістеу', category: 'Actions', level: 'pre-intermediate' },
  { english: 'taste', russian: 'пробовать', kazakh: 'дәмін татып көру', category: 'Actions', level: 'pre-intermediate' },
  { english: 'touch', russian: 'трогать', kazakh: 'ұстау', category: 'Actions', level: 'pre-intermediate' },
  { english: 'think', russian: 'думать', kazakh: 'ойлау', category: 'Actions', level: 'pre-intermediate' },
  { english: 'know', russian: 'знать', kazakh: 'білу', category: 'Actions', level: 'pre-intermediate' },
  { english: 'understand', russian: 'понимать', kazakh: 'түсіну', category: 'Actions', level: 'pre-intermediate' },
  { english: 'remember', russian: 'помнить', kazakh: 'есте сақтау', category: 'Actions', level: 'pre-intermediate' },
  { english: 'forget', russian: 'забывать', kazakh: 'ұмыту', category: 'Actions', level: 'pre-intermediate' },
  { english: 'learn', russian: 'учиться', kazakh: 'үйрену', category: 'Actions', level: 'pre-intermediate' },
  { english: 'teach', russian: 'учить', kazakh: 'үйрету', category: 'Actions', level: 'pre-intermediate' },
  { english: 'study', russian: 'изучать', kazakh: 'оқу', category: 'Actions', level: 'pre-intermediate' },
  { english: 'play', russian: 'играть', kazakh: 'ойнау', category: 'Actions', level: 'pre-intermediate' },
  { english: 'work', russian: 'работать', kazakh: 'жұмыс істеу', category: 'Actions', level: 'pre-intermediate' },
  { english: 'sleep', russian: 'спать', kazakh: 'ұйықтау', category: 'Actions', level: 'pre-intermediate' },
  { english: 'wake up', russian: 'просыпаться', kazakh: 'оянып кету', category: 'Actions', level: 'pre-intermediate' },
  { english: 'eat', russian: 'есть', kazakh: 'жеу', category: 'Actions', level: 'pre-intermediate' },
  { english: 'drink', russian: 'пить', kazakh: 'ішу', category: 'Actions', level: 'pre-intermediate' },
  { english: 'cook', russian: 'готовить', kazakh: 'пісіру', category: 'Actions', level: 'pre-intermediate' },
  { english: 'clean', russian: 'чистить', kazakh: 'тазалау', category: 'Actions', level: 'pre-intermediate' },
  { english: 'wash', russian: 'мыть', kazakh: 'жуу', category: 'Actions', level: 'pre-intermediate' },
  { english: 'buy', russian: 'покупать', kazakh: 'сатып алу', category: 'Actions', level: 'pre-intermediate' },
  { english: 'sell', russian: 'продавать', kazakh: 'сату', category: 'Actions', level: 'pre-intermediate' },
  { english: 'open', russian: 'открывать', kazakh: 'ашу', category: 'Actions', level: 'pre-intermediate' },
  { english: 'close', russian: 'закрывать', kazakh: 'жабу', category: 'Actions', level: 'pre-intermediate' },
  { english: 'start', russian: 'начинать', kazakh: 'бастау', category: 'Actions', level: 'pre-intermediate' },
  { english: 'finish', russian: 'заканчивать', kazakh: 'аяқтау', category: 'Actions', level: 'pre-intermediate' },

  // Adjectives - Прилагательные (50 слов)
  { english: 'big', russian: 'большой', kazakh: 'үлкен', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'small', russian: 'маленький', kazakh: 'кіші', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'tall', russian: 'вы��окий', kazakh: 'биік', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'short', russian: 'короткий', kazakh: 'қысқа', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'long', russian: 'длинный', kazakh: 'ұзын', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'wide', russian: 'широкий', kazakh: 'кең', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'narrow', russian: 'узкий', kazakh: 'тар', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'thick', russian: 'толстый', kazakh: 'жуан', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'thin', russian: 'тонкий', kazakh: 'жіңішке', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'heavy', russian: 'тяжелый', kazakh: 'ауыр', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'light', russian: 'легкий', kazakh: 'жеңіл', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'hard', russian: 'твердый', kazakh: 'қатты', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'soft', russian: 'мягкий', kazakh: 'жұмсақ', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'fast', russian: 'быстрый', kazakh: 'жылдам', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'slow', russian: 'медленный', kazakh: 'баяу', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'new', russian: 'новый', kazakh: 'жаңа', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'old', russian: 'старый', kazakh: 'ескі', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'young', russian: 'молодой', kazakh: 'жас', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'good', russian: 'хороший', kazakh: 'жақсы', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'bad', russian: 'плохой', kazakh: 'жаман', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'beautiful', russian: 'красивый', kazakh: 'әдемі', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'ugly', russian: 'уродливый', kazakh: 'сұмдық', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'clean', russian: 'чистый', kazakh: 'таза', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'dirty', russian: 'грязный', kazakh: 'лас', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'full', russian: 'полный', kazakh: 'толық', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'empty', russian: 'пустой', kazakh: 'бос', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'rich', russian: 'богатый', kazakh: 'бай', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'poor', russian: 'бедный', kazakh: 'кедей', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'easy', russian: 'легкий', kazakh: 'оңай', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'difficult', russian: 'трудный', kazakh: 'қиын', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'strong', russian: 'сильный', kazakh: 'мықты', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'weak', russian: 'слабый', kazakh: 'әлсіз', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'loud', russian: 'громкий', kazakh: 'дауысты', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'quiet', russian: 'тихий', kazakh: 'тыныш', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'safe', russian: 'безопасный', kazakh: 'қауіпсіз', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'dangerous', russian: 'опасный', kazakh: 'қауіпті', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'interesting', russian: 'интересный', kazakh: 'қызықты', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'boring', russian: 'скучный', kazakh: 'жалықтырғыш', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'important', russian: 'важный', kazakh: 'маңызды', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'special', russian: 'особенный', kazakh: 'ерекше', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'famous', russian: 'знаменитый', kazakh: 'атақты', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'popular', russian: 'популярный', kazakh: 'танымал', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'modern', russian: 'современный', kazakh: 'заманауи', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'ancient', russian: 'древний', kazakh: 'ежелгі', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'fresh', russian: 'свежий', kazakh: 'жаңа', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'delicious', russian: 'вкусный', kazakh: 'дәмді', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'sweet', russian: 'сладкий', kazakh: 'тәтті', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'sour', russian: 'кислый', kazakh: 'қышқыл', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'bitter', russian: 'горький', kazakh: 'ащы', category: 'Adjectives', level: 'pre-intermediate' },
  { english: 'spicy', russian: 'острый', kazakh: 'ащы', category: 'Adjectives', level: 'pre-intermediate' },

  // Time - Время (30 слов)
  { english: 'minute', russian: 'минута', kazakh: 'минут', category: 'Time', level: 'pre-intermediate' },
  { english: 'second', russian: 'секунда', kazakh: 'секунд', category: 'Time', level: 'pre-intermediate' },
  { english: 'hour', russian: 'час', kazakh: 'сағат', category: 'Time', level: 'pre-intermediate' },
  { english: 'day', russian: 'день', kazakh: 'күн', category: 'Time', level: 'pre-intermediate' },
  { english: 'week', russian: 'неделя', kazakh: 'апта', category: 'Time', level: 'pre-intermediate' },
  { english: 'fortnight', russian: 'две недели', kazakh: 'екі апта', category: 'Time', level: 'pre-intermediate' },
  { english: 'month', russian: 'месяц', kazakh: 'ай', category: 'Time', level: 'pre-intermediate' },
  { english: 'year', russian: 'год', kazakh: 'жыл', category: 'Time', level: 'pre-intermediate' },
  { english: 'decade', russian: 'десятилетие', kazakh: 'онжылдық', category: 'Time', level: 'pre-intermediate' },
  { english: 'century', russian: 'век', kazakh: 'ғасыр', category: 'Time', level: 'pre-intermediate' },
  { english: 'now', russian: 'сейчас', kazakh: 'қазір', category: 'Time', level: 'pre-intermediate' },
  { english: 'then', russian: 'тогда', kazakh: 'сонда', category: 'Time', level: 'pre-intermediate' },
  { english: 'soon', russian: 'скоро', kazakh: 'жақында', category: 'Time', level: 'pre-intermediate' },
  { english: 'later', russian: 'позже', kazakh: 'кейінірек', category: 'Time', level: 'pre-intermediate' },
  { english: 'early', russian: 'рано', kazakh: 'ерте', category: 'Time', level: 'pre-intermediate' },
  { english: 'late', russian: 'поздно', kazakh: 'кеш', category: 'Time', level: 'pre-intermediate' },
  { english: 'always', russian: 'всегда', kazakh: 'әрқашан', category: 'Time', level: 'pre-intermediate' },
  { english: 'never', russian: 'никогда', kazakh: 'ешқашан', category: 'Time', level: 'pre-intermediate' },
  { english: 'sometimes', russian: 'иногда', kazakh: 'кейде', category: 'Time', level: 'pre-intermediate' },
  { english: 'often', russian: 'часто', kazakh: 'жиі', category: 'Time', level: 'pre-intermediate' },
  { english: 'rarely', russian: 'редко', kazakh: 'сирек', category: 'Time', level: 'pre-intermediate' },
  { english: 'daily', russian: 'ежедневно', kazakh: 'күн сайын', category: 'Time', level: 'pre-intermediate' },
  { english: 'weekly', russian: 'еженедельно', kazakh: 'апта сайын', category: 'Time', level: 'pre-intermediate' },
  { english: 'monthly', russian: 'ежемесячно', kazakh: 'ай сайын', category: 'Time', level: 'pre-intermediate' },
  { english: 'yearly', russian: 'ежегодно', kazakh: 'жыл сайын', category: 'Time', level: 'pre-intermediate' },
  { english: 'past', russian: 'прошлое', kazakh: 'өткен', category: 'Time', level: 'pre-intermediate' },
  { english: 'present', russian: 'настоящее', kazakh: 'қазіргі', category: 'Time', level: 'pre-intermediate' },
  { english: 'future', russian: 'будущее', kazakh: 'болашақ', category: 'Time', level: 'pre-intermediate' },
  { english: 'beginning', russian: 'начало', kazakh: 'басы', category: 'Time', level: 'pre-intermediate' },
  { english: 'end', russian: 'конец', kazakh: 'соңы', category: 'Time', level: 'pre-intermediate' },

  // Shopping - Покупки (30 слов)
  { english: 'money', russian: 'деньги', kazakh: 'ақша', category: 'Shopping', level: 'pre-intermediate' },
  { english: 'price', russian: 'цена', kazakh: 'баға', category: 'Shopping', level: 'pre-intermediate' },
  { english: 'cost', russian: 'стоимость', kazakh: 'құн', category: 'Shopping', level: 'pre-intermediate' },
  { english: 'expensive', russian: 'дорогой', kazakh: 'қымбат', category: 'Shopping', level: 'pre-intermediate' },
  { english: 'cheap', russian: 'дешевый', kazakh: 'арзан', category: 'Shopping', level: 'pre-intermediate' },
  { english: 'free', russian: 'бесплатный', kazakh: 'тегін', category: 'Shopping', level: 'pre-intermediate' },
  { english: 'discount', russian: 'скидка', kazakh: 'жеңілдік', category: 'Shopping', level: 'pre-intermediate' },
  { english: 'sale', russian: 'распродажа', kazakh: 'сату', category: 'Shopping', level: 'pre-intermediate' },
  { english: 'shopping', russian: 'покупки', kazakh: 'сатып алу', category: 'Shopping', level: 'pre-intermediate' },
  { english: 'customer', russian: 'покупатель', kazakh: 'сатып алушы', category: 'Shopping', level: 'pre-intermediate' },
  { english: 'seller', russian: 'продавец', kazakh: 'сатушы', category: 'Shopping', level: 'pre-intermediate' },
  { english: 'cashier', russian: 'кассир', kazakh: 'кассир', category: 'Shopping', level: 'pre-intermediate' },
  { english: 'receipt', russian: 'чек', kazakh: 'түбіртек', category: 'Shopping', level: 'pre-intermediate' },
  { english: 'change', russian: 'сдача', kazakh: 'қайтарым', category: 'Shopping', level: 'pre-intermediate' },
  { english: 'cash', russian: 'наличные', kazakh: 'қолма-қол ақша', category: 'Shopping', level: 'pre-intermediate' },
  { english: 'card', russian: 'карта', kazakh: 'карта', category: 'Shopping', level: 'pre-intermediate' },
  { english: 'wallet', russian: 'кошелек', kazakh: 'әмиян', category: 'Shopping', level: 'pre-intermediate' },
  { english: 'purse', russian: 'сумочка', kazakh: 'сөмке', category: 'Shopping', level: 'pre-intermediate' },
  { english: 'bag', russian: 'сумка', kazakh: 'сөмке', category: 'Shopping', level: 'pre-intermediate' },
  { english: 'basket', russian: 'корзина', kazakh: 'себет', category: 'Shopping', level: 'pre-intermediate' },
  { english: 'cart', russian: 'тележка', kazakh: 'арба', category: 'Shopping', level: 'pre-intermediate' },
  { english: 'package', russian: 'упаковка', kazakh: 'орам', category: 'Shopping', level: 'pre-intermediate' },
  { english: 'size', russian: 'размер', kazakh: 'өлшем', category: 'Shopping', level: 'pre-intermediate' },
  { english: 'quality', russian: 'качество', kazakh: 'сапа', category: 'Shopping', level: 'pre-intermediate' },
  { english: 'brand', russian: 'бренд', kazakh: 'бренд', category: 'Shopping', level: 'pre-intermediate' },
  { english: 'label', russian: 'этикетка', kazakh: 'белгі', category: 'Shopping', level: 'pre-intermediate' },
  { english: 'barcode', russian: 'штрих-код', kazakh: 'штрих-код', category: 'Shopping', level: 'pre-intermediate' },
  { english: 'shelf', russian: 'полка', kazakh: 'сөре', category: 'Shopping', level: 'pre-intermediate' },
  { english: 'aisle', russian: 'проход', kazakh: 'өту жолы', category: 'Shopping', level: 'pre-intermediate' },
  { english: 'checkout', russian: 'касса', kazakh: 'касса', category: 'Shopping', level: 'pre-intermediate' },

  // Health - Здоровье (30 слов)
  { english: 'health', russian: 'здоровье', kazakh: 'денсаулық', category: 'Health', level: 'pre-intermediate' },
  { english: 'illness', russian: 'болезнь', kazakh: 'ауру', category: 'Health', level: 'pre-intermediate' },
  { english: 'sick', russian: 'больной', kazakh: 'ауру', category: 'Health', level: 'pre-intermediate' },
  { english: 'healthy', russian: 'здоровый', kazakh: 'сау', category: 'Health', level: 'pre-intermediate' },
  { english: 'pain', russian: 'боль', kazakh: 'ауырсыну', category: 'Health', level: 'pre-intermediate' },
  { english: 'headache', russian: 'головная боль', kazakh: 'бас ауыруы', category: 'Health', level: 'pre-intermediate' },
  { english: 'stomachache', russian: 'боль в животе', kazakh: 'қарын ауыруы', category: 'Health', level: 'pre-intermediate' },
  { english: 'toothache', russian: 'зубная боль', kazakh: 'тіс ауыруы', category: 'Health', level: 'pre-intermediate' },
  { english: 'fever', russian: 'жар', kazakh: 'қызба', category: 'Health', level: 'pre-intermediate' },
  { english: 'cold', russian: 'простуда', kazakh: 'аузу', category: 'Health', level: 'pre-intermediate' },
  { english: 'flu', russian: 'грипп', kazakh: 'тұмау', category: 'Health', level: 'pre-intermediate' },
  { english: 'cough', russian: 'кашель', kazakh: 'жөтел', category: 'Health', level: 'pre-intermediate' },
  { english: 'sneeze', russian: 'чихание', kazakh: 'түшкіру', category: 'Health', level: 'pre-intermediate' },
  { english: 'medicine', russian: 'лекарство', kazakh: 'дәрі', category: 'Health', level: 'pre-intermediate' },
  { english: 'pill', russian: 'таблетка', kazakh: 'таблетка', category: 'Health', level: 'pre-intermediate' },
  { english: 'injection', russian: 'укол', kazakh: 'инъекция', category: 'Health', level: 'pre-intermediate' },
  { english: 'bandage', russian: 'бинт', kazakh: 'таңғыш', category: 'Health', level: 'pre-intermediate' },
  { english: 'wound', russian: 'рана', kazakh: 'жара', category: 'Health', level: 'pre-intermediate' },
  { english: 'injury', russian: 'травма', kazakh: 'жарақат', category: 'Health', level: 'pre-intermediate' },
  { english: 'accident', russian: 'несчастный случай', kazakh: 'жазатайым оқиға', category: 'Health', level: 'pre-intermediate' },
  { english: 'emergency', russian: 'экстренный случай', kazakh: 'төтенше жағдай', category: 'Health', level: 'pre-intermediate' },
  { english: 'treatment', russian: 'лечение', kazakh: 'емдеу', category: 'Health', level: 'pre-intermediate' },
  { english: 'cure', russian: 'лекарство', kazakh: 'ем', category: 'Health', level: 'pre-intermediate' },
  { english: 'operation', russian: 'операция', kazakh: 'операция', category: 'Health', level: 'pre-intermediate' },
  { english: 'patient', russian: 'пациент', kazakh: 'науқас', category: 'Health', level: 'pre-intermediate' },
  { english: 'appointment', russian: 'прием', kazakh: 'қабылдау', category: 'Health', level: 'pre-intermediate' },
  { english: 'symptom', russian: 'симптом', kazakh: 'белгі', category: 'Health', level: 'pre-intermediate' },
  { english: 'diagnosis', russian: 'диагноз', kazakh: 'диагноз', category: 'Health', level: 'pre-intermediate' },
  { english: 'exercise', russian: 'упражнение', kazakh: 'жаттығу', category: 'Health', level: 'pre-intermediate' },
  { english: 'diet', russian: 'диета', kazakh: 'диета', category: 'Health', level: 'pre-intermediate' },

  // Travel - Путешествия (30 слов)
  { english: 'travel', russian: 'путешествие', kazakh: 'саяхат', category: 'Travel', level: 'pre-intermediate' },
  { english: 'trip', russian: 'поездка', kazakh: 'сапар', category: 'Travel', level: 'pre-intermediate' },
  { english: 'journey', russian: 'путешествие', kazakh: 'жол', category: 'Travel', level: 'pre-intermediate' },
  { english: 'vacation', russian: 'отпуск', kazakh: 'демалыс', category: 'Travel', level: 'pre-intermediate' },
  { english: 'holiday', russian: 'отдых', kazakh: 'мереке', category: 'Travel', level: 'pre-intermediate' },
  { english: 'tourist', russian: 'турист', kazakh: 'турист', category: 'Travel', level: 'pre-intermediate' },
  { english: 'guide', russian: 'гид', kazakh: 'гид', category: 'Travel', level: 'pre-intermediate' },
  { english: 'passport', russian: 'паспорт', kazakh: 'паспорт', category: 'Travel', level: 'pre-intermediate' },
  { english: 'visa', russian: 'виза', kazakh: 'виза', category: 'Travel', level: 'pre-intermediate' },
  { english: 'ticket', russian: 'билет', kazakh: 'билет', category: 'Travel', level: 'pre-intermediate' },
  { english: 'luggage', russian: 'багаж', kazakh: 'жүк', category: 'Travel', level: 'pre-intermediate' },
  { english: 'suitcase', russian: 'чемодан', kazakh: 'чемодан', category: 'Travel', level: 'pre-intermediate' },
  { english: 'backpack', russian: 'рюкзак', kazakh: 'рюкзак', category: 'Travel', level: 'pre-intermediate' },
  { english: 'map', russian: 'карта', kazakh: 'карта', category: 'Travel', level: 'pre-intermediate' },
  { english: 'direction', russian: 'направление', kazakh: 'бағыт', category: 'Travel', level: 'pre-intermediate' },
  { english: 'north', russian: 'север', kazakh: 'солтүстік', category: 'Travel', level: 'pre-intermediate' },
  { english: 'south', russian: 'юг', kazakh: 'оңтүстік', category: 'Travel', level: 'pre-intermediate' },
  { english: 'east', russian: 'восток', kazakh: 'шығыс', category: 'Travel', level: 'pre-intermediate' },
  { english: 'west', russian: 'запад', kazakh: 'батыс', category: 'Travel', level: 'pre-intermediate' },
  { english: 'left', russian: 'левый', kazakh: 'сол', category: 'Travel', level: 'pre-intermediate' },
  { english: 'right', russian: 'правый', kazakh: 'оң', category: 'Travel', level: 'pre-intermediate' },
  { english: 'straight', russian: 'прямо', kazakh: 'түзу', category: 'Travel', level: 'pre-intermediate' },
  { english: 'distance', russian: 'расстояние', kazakh: 'қашықтық', category: 'Travel', level: 'pre-intermediate' },
  { english: 'destination', russian: 'место назначения', kazakh: 'бару орны', category: 'Travel', level: 'pre-intermediate' },
  { english: 'arrival', russian: 'прибытие', kazakh: 'келу', category: 'Travel', level: 'pre-intermediate' },
  { english: 'departure', russian: 'отправление', kazakh: 'кету', category: 'Travel', level: 'pre-intermediate' },
  { english: 'delay', russian: 'задержка', kazakh: 'кешігу', category: 'Travel', level: 'pre-intermediate' },
  { english: 'cancel', russian: 'отменить', kazakh: 'болдырмау', category: 'Travel', level: 'pre-intermediate' },
  { english: 'booking', russian: 'бронирование', kazakh: 'брондау', category: 'Travel', level: 'pre-intermediate' },
  { english: 'reservation', russian: 'резервирование', kazakh: 'брондау', category: 'Travel', level: 'pre-intermediate' },

  // Hobbies - Хобби (30 слов)
  { english: 'hobby', russian: 'хобби', kazakh: 'хобби', category: 'Hobbies', level: 'pre-intermediate' },
  { english: 'interest', russian: 'интерес', kazakh: 'қызығушылық', category: 'Hobbies', level: 'pre-intermediate' },
  { english: 'painting', russian: 'рисование', kazakh: 'сурет салу', category: 'Hobbies', level: 'pre-intermediate' },
  { english: 'drawing', russian: 'рисунок', kazakh: 'сурет', category: 'Hobbies', level: 'pre-intermediate' },
  { english: 'photography', russian: 'фотография', kazakh: 'фотография', category: 'Hobbies', level: 'pre-intermediate' },
  { english: 'collecting', russian: 'коллекционирование', kazakh: 'жинау', category: 'Hobbies', level: 'pre-intermediate' },
  { english: 'collection', russian: 'коллекция', kazakh: 'жинақ', category: 'Hobbies', level: 'pre-intermediate' },
  { english: 'gardening', russian: 'садоводство', kazakh: 'бағбандық', category: 'Hobbies', level: 'pre-intermediate' },
  { english: 'cooking', russian: 'готовка', kazakh: 'тамақ дайындау', category: 'Hobbies', level: 'pre-intermediate' },
  { english: 'baking', russian: 'выпечка', kazakh: 'пісіру', category: 'Hobbies', level: 'pre-intermediate' },
  { english: 'knitting', russian: 'вязание', kazakh: 'тоқу', category: 'Hobbies', level: 'pre-intermediate' },
  { english: 'sewing', russian: 'шитье', kazakh: 'тігу', category: 'Hobbies', level: 'pre-intermediate' },
  { english: 'fishing', russian: 'рыбалка', kazakh: 'балық аулау', category: 'Hobbies', level: 'pre-intermediate' },
  { english: 'hunting', russian: 'охота', kazakh: 'аңшылық', category: 'Hobbies', level: 'pre-intermediate' },
  { english: 'camping', russian: 'кемпинг', kazakh: 'кемпинг', category: 'Hobbies', level: 'pre-intermediate' },
  { english: 'hiking', russian: 'пеший туризм', kazakh: 'жаяу серуен', category: 'Hobbies', level: 'pre-intermediate' },
  { english: 'climbing', russian: 'альпинизм', kazakh: 'өрмелеу', category: 'Hobbies', level: 'pre-intermediate' },
  { english: 'surfing', russian: 'серфинг', kazakh: 'серфинг', category: 'Hobbies', level: 'pre-intermediate' },
  { english: 'skating', russian: 'катание', kazakh: 'сырғанау', category: 'Hobbies', level: 'pre-intermediate' },
  { english: 'dancing', russian: 'танцы', kazakh: 'би', category: 'Hobbies', level: 'pre-intermediate' },
  { english: 'singing', russian: 'пение', kazakh: 'ән айту', category: 'Hobbies', level: 'pre-intermediate' },
  { english: 'instrument', russian: 'инструмент', kazakh: 'аспап', category: 'Hobbies', level: 'pre-intermediate' },
  { english: 'guitar', russian: 'гитара', kazakh: 'гитара', category: 'Hobbies', level: 'pre-intermediate' },
  { english: 'piano', russian: 'пианино', kazakh: 'фортепиано', category: 'Hobbies', level: 'pre-intermediate' },
  { english: 'drum', russian: 'барабан', kazakh: 'дауыл', category: 'Hobbies', level: 'pre-intermediate' },
  { english: 'violin', russian: 'скрипка', kazakh: 'скрипка', category: 'Hobbies', level: 'pre-intermediate' },
  { english: 'flute', russian: 'флейта', kazakh: 'үйілдірік', category: 'Hobbies', level: 'pre-intermediate' },
  { english: 'chess', russian: 'шахматы', kazakh: 'шахмат', category: 'Hobbies', level: 'pre-intermediate' },
  { english: 'puzzle', russian: 'головоломка', kazakh: 'жұмбақ', category: 'Hobbies', level: 'pre-intermediate' },
  { english: 'game', russian: 'игра', kazakh: 'ойын', category: 'Hobbies', level: 'pre-intermediate' },

  // ==================== INTERMEDIATE (начало - 300+ слов) ====================
  
  // Advanced Vocabulary (40 слов)
  { english: 'achieve', russian: 'достигать', kazakh: 'жету', category: 'Advanced', level: 'intermediate' },
  { english: 'success', russian: 'успех', kazakh: 'табыс', category: 'Advanced', level: 'intermediate' },
  { english: 'failure', russian: 'неудача', kazakh: 'сәтсіздік', category: 'Advanced', level: 'intermediate' },
  { english: 'challenge', russian: 'вызов', kazakh: 'сын', category: 'Advanced', level: 'intermediate' },
  { english: 'opportunity', russian: 'возможность', kazakh: 'мүм��індік', category: 'Advanced', level: 'intermediate' },
  { english: 'advantage', russian: 'преимущество', kazakh: 'артықшылық', category: 'Advanced', level: 'intermediate' },
  { english: 'disadvantage', russian: 'недостаток', kazakh: 'кемшілік', category: 'Advanced', level: 'intermediate' },
  { english: 'decision', russian: 'решение', kazakh: 'шешім', category: 'Advanced', level: 'intermediate' },
  { english: 'choice', russian: 'выбор', kazakh: 'таңдау', category: 'Advanced', level: 'intermediate' },
  { english: 'opinion', russian: 'мнение', kazakh: 'пікір', category: 'Advanced', level: 'intermediate' },
  { english: 'idea', russian: 'идея', kazakh: 'идея', category: 'Advanced', level: 'intermediate' },
  { english: 'thought', russian: 'мысль', kazakh: 'ой', category: 'Advanced', level: 'intermediate' },
  { english: 'belief', russian: 'вера', kazakh: 'сенім', category: 'Advanced', level: 'intermediate' },
  { english: 'knowledge', russian: 'знание', kazakh: 'білім', category: 'Advanced', level: 'intermediate' },
  { english: 'wisdom', russian: 'мудрость', kazakh: 'даналық', category: 'Advanced', level: 'intermediate' },
  { english: 'experience', russian: 'опыт', kazakh: 'тәжірибе', category: 'Advanced', level: 'intermediate' },
  { english: 'skill', russian: 'навык', kazakh: 'дағды', category: 'Advanced', level: 'intermediate' },
  { english: 'ability', russian: 'способность', kazakh: 'қабілет', category: 'Advanced', level: 'intermediate' },
  { english: 'talent', russian: 'талант', kazakh: 'талант', category: 'Advanced', level: 'intermediate' },
  { english: 'gift', russian: 'дар', kazakh: 'дарын', category: 'Advanced', level: 'intermediate' },
  { english: 'effort', russian: 'усилие', kazakh: 'күш', category: 'Advanced', level: 'intermediate' },
  { english: 'attempt', russian: 'попытка', kazakh: 'әрекет', category: 'Advanced', level: 'intermediate' },
  { english: 'practice', russian: 'практика', kazakh: 'жаттығу', category: 'Advanced', level: 'intermediate' },
  { english: 'progress', russian: 'прогресс', kazakh: 'алға', category: 'Advanced', level: 'intermediate' },
  { english: 'improvement', russian: 'улучшение', kazakh: 'жақсарту', category: 'Advanced', level: 'intermediate' },
  { english: 'development', russian: 'развитие', kazakh: 'даму', category: 'Advanced', level: 'intermediate' },
  { english: 'growth', russian: 'рост', kazakh: 'өсу', category: 'Advanced', level: 'intermediate' },
  { english: 'increase', russian: 'увеличение', kazakh: 'өсім', category: 'Advanced', level: 'intermediate' },
  { english: 'decrease', russian: 'уменьшение', kazakh: 'кему', category: 'Advanced', level: 'intermediate' },
  { english: 'change', russian: 'изменение', kazakh: 'өзгеріс', category: 'Advanced', level: 'intermediate' },
  { english: 'difference', russian: 'разница', kazakh: 'айырма', category: 'Advanced', level: 'intermediate' },
  { english: 'similarity', russian: 'сходство', kazakh: 'ұқсастық', category: 'Advanced', level: 'intermediate' },
  { english: 'comparison', russian: 'сравнение', kazakh: 'салыстыру', category: 'Advanced', level: 'intermediate' },
  { english: 'contrast', russian: 'контраст', kazakh: 'қарама-қайшылық', category: 'Advanced', level: 'intermediate' },
  { english: 'example', russian: 'пример', kazakh: 'мысал', category: 'Advanced', level: 'intermediate' },
  { english: 'evidence', russian: 'доказательство', kazakh: 'дәлел', category: 'Advanced', level: 'intermediate' },
  { english: 'proof', russian: 'доказательство', kazakh: 'дәлел', category: 'Advanced', level: 'intermediate' },
  { english: 'reason', russian: 'причина', kazakh: 'себеп', category: 'Advanced', level: 'intermediate' },
  { english: 'cause', russian: 'причина', kazakh: 'себеп', category: 'Advanced', level: 'intermediate' },
  { english: 'effect', russian: 'эффект', kazakh: 'әсер', category: 'Advanced', level: 'intermediate' },
];
