// База данных для уровня BEGINNER - 300 слов с описаниями

export interface Word {
  english: string;
  russian: string;
  kazakh: string;
  category: string;
  descriptionRu: string;
  descriptionKz: string;
}

// 300 слов для начинающих по категориям
export const BEGINNER_WORDS: Word[] = [
  // Animals - 30 слов
  { english: 'cat', russian: 'кот', kazakh: 'мысық', category: 'Animals', descriptionRu: 'Домашнее животное, которое мяукает', descriptionKz: 'Мияулайтын үй жануары' },
  { english: 'dog', russian: 'собака', kazakh: 'ит', category: 'Animals', descriptionRu: 'Домашнее животное, которое лает', descriptionKz: 'Үретін үй жануары' },
  { english: 'bird', russian: 'птица', kazakh: 'құс', category: 'Animals', descriptionRu: 'Животное, которое летает и поёт', descriptionKz: 'Ұшып, сайрайтын жануар' },
  { english: 'fish', russian: 'рыба', kazakh: 'балық', category: 'Animals', descriptionRu: 'Животное, которое плавает в воде', descriptionKz: 'Суда жүзетін жануар' },
  { english: 'rabbit', russian: 'кролик', kazakh: 'қоян', category: 'Animals', descriptionRu: 'Животное с длинными ушами, любит морковку', descriptionKz: 'Ұзын құлақты, сәбізді жақсы көретін жануар' },
  { english: 'horse', russian: 'лошадь', kazakh: 'жылқы', category: 'Animals', descriptionRu: 'Большое животное, на котором можно ездить', descriptionKz: 'Мінуге болатын үлкен жануар' },
  { english: 'cow', russian: 'корова', kazakh: 'сиыр', category: 'Animals', descriptionRu: 'Животное, которое даёт молоко', descriptionKz: 'Сүт беретін жануар' },
  { english: 'pig', russian: 'свинья', kazakh: 'шошқа', category: 'Animals', descriptionRu: 'Розовое животное, которое хрюкает', descriptionKz: 'Қоңқылдайтын қызғылт жануар' },
  { english: 'chicken', russian: 'курица', kazakh: 'тауық', category: 'Animals', descriptionRu: 'Птица, которая несёт яйца', descriptionKz: 'Жұмыртқа салатын құс' },
  { english: 'duck', russian: 'утка', kazakh: 'үйрек', category: 'Animals', descriptionRu: 'Птица, которая плавает и крякает', descriptionKz: 'Жүзетін және ырылдайтын құс' },
  { english: 'elephant', russian: 'слон', kazakh: 'піл', category: 'Animals', descriptionRu: 'Очень большое животное с хоботом', descriptionKz: 'Өте үлкен, мұрынды жануар' },
  { english: 'lion', russian: 'лев', kazakh: 'арыстан', category: 'Animals', descriptionRu: 'Царь зверей с большой гривой', descriptionKz: 'Үлкен жалды аңдар патшасы' },
  { english: 'tiger', russian: 'тигр', kazakh: 'жолбарыс', category: 'Animals', descriptionRu: 'Большая полосатая кошка', descriptionKz: 'Үлкен жолақты мысық' },
  { english: 'bear', russian: 'медведь', kazakh: 'аю', category: 'Animals', descriptionRu: 'Большое животное, любит мёд', descriptionKz: 'Балды жақсы көретін үлкен жануар' },
  { english: 'wolf', russian: 'волк', kazakh: 'қасқыр', category: 'Animals', descriptionRu: 'Дикое животное, похожее на собаку', descriptionKz: 'Итке ұқсас жабайы жануар' },
  { english: 'fox', russian: 'лиса', kazakh: 'түлкі', category: 'Animals', descriptionRu: 'Рыжее хитрое животное', descriptionKz: 'Қызыл айлакер жануар' },
  { english: 'monkey', russian: 'обезьяна', kazakh: 'маймыл', category: 'Animals', descriptionRu: 'Животное, которое лазает по деревьям', descriptionKz: 'Ағашқа өрмелейтін жануар' },
  { english: 'mouse', russian: 'мышь', kazakh: 'тышқан', category: 'Animals', descriptionRu: 'Маленькое животное с длинным хвостом', descriptionKz: 'Ұзын құйрықты кішкентай жануар' },
  { english: 'frog', russian: 'лягушка', kazakh: 'бақа', category: 'Animals', descriptionRu: 'Зелёное животное, которое прыгает и квакает', descriptionKz: 'Секіретін және қарылдайтын жасыл жануар' },
  { english: 'snake', russian: 'змея', kazakh: 'жылан', category: 'Animals', descriptionRu: 'Длинное животное без ног', descriptionKz: 'Аяғы жоқ ұзын жануар' },
  { english: 'butterfly', russian: 'бабочка', kazakh: 'көбелек', category: 'Animals', descriptionRu: 'Насекомое с красивыми крыльями', descriptionKz: 'Әдемі қанатты жәндік' },
  { english: 'bee', russian: 'пчела', kazakh: 'ара', category: 'Animals', descriptionRu: 'Насекомое, которое делает мёд', descriptionKz: 'Бал жасайтын жәндік' },
  { english: 'spider', russian: 'паук', kazakh: 'өрмекші', category: 'Animals', descriptionRu: 'Насекомое с восемью ногами, плетёт паутину', descriptionKz: 'Сегіз аяқты, тор тоқитын жәндік' },
  { english: 'dolphin', russian: 'дельфин', kazakh: 'дельфин', category: 'Animals', descriptionRu: 'Умное морское животное', descriptionKz: 'Ақылды теңіз жануары' },
  { english: 'whale', russian: 'кит', kazakh: 'кит', category: 'Animals', descriptionRu: 'Самое большое морское животное', descriptionKz: 'Ең үлкен теңіз жануары' },
  { english: 'shark', russian: 'акула', kazakh: 'акула', category: 'Animals', descriptionRu: 'Опасная большая рыба с зубами', descriptionKz: 'Тісті қауіпті үлкен балық' },
  { english: 'penguin', russian: 'пингвин', kazakh: 'пингвин', category: 'Animals', descriptionRu: 'Птица, которая не летает, живёт в холоде', descriptionKz: 'Ұшпайтын, суықта өмір сүретін құс' },
  { english: 'parrot', russian: 'попугай', kazakh: 'тотықұс', category: 'Animals', descriptionRu: 'Яркая птица, которая умеет говорить', descriptionKz: 'Сөйлей алатын әдемі құс' },
  { english: 'sheep', russian: 'овца', kazakh: 'қой', category: 'Animals', descriptionRu: 'Животное с шерстью, даёт нам шерсть', descriptionKz: 'Жүні бар, бізге жүн беретін жануар' },
  { english: 'goat', russian: 'коза', kazakh: 'ешкі', category: 'Animals', descriptionRu: 'Животное с рогами, даёт молоко', descriptionKz: 'Мүйізді, сүт беретін жануар' },
  
  // Colors - 20 слов
  { english: 'red', russian: 'красный', kazakh: 'қызыл', category: 'Colors', descriptionRu: 'Цвет яблока и помидора', descriptionKz: 'Алма мен қызанақтың түсі' },
  { english: 'blue', russian: 'синий', kazakh: 'көк', category: 'Colors', descriptionRu: 'Цвет неба и моря', descriptionKz: 'Аспан мен теңіздің түсі' },
  { english: 'green', russian: 'зеленый', kazakh: 'жасыл', category: 'Colors', descriptionRu: 'Цвет травы и листьев', descriptionKz: 'Шөп пен жапырақтың түсі' },
  { english: 'yellow', russian: 'желтый', kazakh: 'сары', category: 'Colors', descriptionRu: 'Цвет солнца и банана', descriptionKz: 'Күн мен банан түсі' },
  { english: 'black', russian: 'черный', kazakh: 'қара', category: 'Colors', descriptionRu: 'Цвет ночи', descriptionKz: 'Түннің түсі' },
  { english: 'white', russian: 'белый', kazakh: 'ақ', category: 'Colors', descriptionRu: 'Цвет снега и молока', descriptionKz: 'Қар мен сүттің түсі' },
  { english: 'orange', russian: 'оранжевый', kazakh: 'сарғыш', category: 'Colors', descriptionRu: 'Цвет апельсина', descriptionKz: 'Апельсиннің түсі' },
  { english: 'purple', russian: 'фиолетовый', kazakh: 'күлгін', category: 'Colors', descriptionRu: 'Цвет винограда', descriptionKz: 'Жүзімнің түсі' },
  { english: 'pink', russian: 'розовый', kazakh: 'қызғылт', category: 'Colors', descriptionRu: 'Цвет розы', descriptionKz: 'Раушан гүлінің түсі' },
  { english: 'brown', russian: 'коричневый', kazakh: 'қоңыр', category: 'Colors', descriptionRu: 'Цвет шоколада и дерева', descriptionKz: 'Шоколад пен ағаштың түсі' },
  { english: 'gray', russian: 'серый', kazakh: 'сұр', category: 'Colors', descriptionRu: 'Цвет облака', descriptionKz: 'Бұлттың түсі' },
  { english: 'silver', russian: 'серебряный', kazakh: 'күміс', category: 'Colors', descriptionRu: 'Блестящий серый цвет', descriptionKz: 'Жылтыр сұр түс' },
  { english: 'gold', russian: 'золотой', kazakh: 'алтын', category: 'Colors', descriptionRu: 'Блестящий желтый цвет', descriptionKz: 'Жылтыр сары түс' },
  { english: 'light', russian: 'светлый', kazakh: 'ашық', category: 'Colors', descriptionRu: 'Не темный цвет', descriptionKz: 'Қара емес түс' },
  { english: 'dark', russian: 'темный', kazakh: 'қою', category: 'Colors', descriptionRu: 'Не светлый цвет', descriptionKz: 'Ашық емес түс' },
  { english: 'bright', russian: 'яркий', kazakh: 'жарқын', category: 'Colors', descriptionRu: 'Очень заметный цвет', descriptionKz: 'Өте көрінетін түс' },
  { english: 'colorful', russian: 'красочный', kazakh: 'түрлі-түсті', category: 'Colors', descriptionRu: 'Много разных цветов', descriptionKz: 'Көп әр түрлі түстер' },
  { english: 'transparent', russian: 'прозрачный', kazakh: 'мөлдір', category: 'Colors', descriptionRu: 'Можно видеть сквозь него, как стекло', descriptionKz: 'Оның арқылы көруге болады, шыны сияқты' },
  { english: 'shiny', russian: 'блестящий', kazakh: 'жылтыр', category: 'Colors', descriptionRu: 'Отражает свет', descriptionKz: 'Жарықты шағылыстырады' },
  { english: 'pale', russian: 'бледный', kazakh: 'ашық түсті', category: 'Colors', descriptionRu: 'Очень светлый оттенок', descriptionKz: 'Өте ашық реңк' },
  
  // Numbers - 30 слов
  { english: 'zero', russian: 'ноль', kazakh: 'нөл', category: 'Numbers', descriptionRu: 'Ничего, пусто', descriptionKz: 'Ештеңе жоқ, бос' },
  { english: 'one', russian: 'один', kazakh: 'бір', category: 'Numbers', descriptionRu: 'Первое число', descriptionKz: 'Бірінші сан' },
  { english: 'two', russian: 'два', kazakh: 'екі', category: 'Numbers', descriptionRu: 'Один плюс один', descriptionKz: 'Бір қосу бір' },
  { english: 'three', russian: 'три', kazakh: 'үш', category: 'Numbers', descriptionRu: 'Два плюс один', descriptionKz: 'Екі қосу бір' },
  { english: 'four', russian: 'четыре', kazakh: 'төрт', category: 'Numbers', descriptionRu: 'Три плюс один', descriptionKz: 'Үш қосу бір' },
  { english: 'five', russian: 'пять', kazakh: 'бес', category: 'Numbers', descriptionRu: 'Пальцев на одной руке', descriptionKz: 'Бір қолдағы саусақтар' },
  { english: 'six', russian: 'шесть', kazakh: 'алты', category: 'Numbers', descriptionRu: 'Пять плюс один', descriptionKz: 'Бес қосу бір' },
  { english: 'seven', russian: 'семь', kazakh: 'жеті', category: 'Numbers', descriptionRu: 'Дней в неделе', descriptionKz: 'Аптадағы күндер' },
  { english: 'eight', russian: 'восемь', kazakh: 'сегіз', category: 'Numbers', descriptionRu: 'Семь плюс один', descriptionKz: 'Жеті қосу бір' },
  { english: 'nine', russian: 'девять', kazakh: 'тоғыз', category: 'Numbers', descriptionRu: 'Восемь плюс один', descriptionKz: 'Сегіз қосу бір' },
  { english: 'ten', russian: 'десять', kazakh: 'он', category: 'Numbers', descriptionRu: 'Пальцев на двух руках', descriptionKz: 'Екі қолдағы саусақтар' },
  { english: 'eleven', russian: 'одиннадцать', kazakh: 'он бір', category: 'Numbers', descriptionRu: 'Десять плюс один', descriptionKz: 'Он қосу бір' },
  { english: 'twelve', russian: 'двенадцать', kazakh: 'он екі', category: 'Numbers', descriptionRu: 'Месяцев в году', descriptionKz: 'Жылдағы айлар' },
  { english: 'thirteen', russian: 'тринадцать', kazakh: 'он үш', category: 'Numbers', descriptionRu: 'Двенадцать плюс один', descriptionKz: 'Он екі қосу бір' },
  { english: 'fourteen', russian: 'четырнадцать', kazakh: 'он төрт', category: 'Numbers', descriptionRu: 'Тринадцать плюс один', descriptionKz: 'Он үш қосу бір' },
  { english: 'fifteen', russian: 'пятнадцать', kazakh: 'он бес', category: 'Numbers', descriptionRu: 'Четырнадцать плюс один', descriptionKz: 'Он төрт қосу бір' },
  { english: 'sixteen', russian: 'шестнадцать', kazakh: 'он алты', category: 'Numbers', descriptionRu: 'Пятнадцать плюс один', descriptionKz: 'Он бес қосу бір' },
  { english: 'seventeen', russian: 'семнадцать', kazakh: 'он жеті', category: 'Numbers', descriptionRu: 'Шестнадцать плюс один', descriptionKz: 'Он алты қосу бір' },
  { english: 'eighteen', russian: 'восемнадцать', kazakh: 'он сегіз', category: 'Numbers', descriptionRu: 'Семнадцать плюс один', descriptionKz: 'Он жеті қосу бір' },
  { english: 'nineteen', russian: 'девятнадцать', kazakh: 'он тоғыз', category: 'Numbers', descriptionRu: 'Восемнадцать плюс один', descriptionKz: 'Он сегіз қосу бір' },
  { english: 'twenty', russian: 'двадцать', kazakh: 'жиырма', category: 'Numbers', descriptionRu: 'Два раза по десять', descriptionKz: 'Екі рет он' },
  { english: 'thirty', russian: 'тридцать', kazakh: 'отыз', category: 'Numbers', descriptionRu: 'Три раза по десять', descriptionKz: 'Үш рет он' },
  { english: 'forty', russian: 'сорок', kazakh: 'қырық', category: 'Numbers', descriptionRu: 'Четыре раза по десять', descriptionKz: 'Төрт рет он' },
  { english: 'fifty', russian: 'пятьдесят', kazakh: 'елу', category: 'Numbers', descriptionRu: 'Пять раз по десять', descriptionKz: 'Бес рет он' },
  { english: 'sixty', russian: 'шестьдесят', kazakh: 'алпыс', category: 'Numbers', descriptionRu: 'Шесть раз по десять', descriptionKz: 'Алты рет он' },
  { english: 'seventy', russian: 'семьдесят', kazakh: 'жетпіс', category: 'Numbers', descriptionRu: 'Семь раз по десять', descriptionKz: 'Жеті рет он' },
  { english: 'eighty', russian: 'восемьдесят', kazakh: 'сексен', category: 'Numbers', descriptionRu: 'Восемь раз по десять', descriptionKz: 'Сегіз рет он' },
  { english: 'ninety', russian: 'девяносто', kazakh: 'тоқсан', category: 'Numbers', descriptionRu: 'Девять раз по десять', descriptionKz: 'Тоғыз рет он' },
  { english: 'hundred', russian: 'сто', kazakh: 'жүз', category: 'Numbers', descriptionRu: 'Десять раз по десять', descriptionKz: 'Он рет он' },
  { english: 'thousand', russian: 'тысяча', kazakh: 'мың', category: 'Numbers', descriptionRu: 'Очень большое число', descriptionKz: 'Өте үлкен сан' },

  // Family - 20 слов
  { english: 'mother', russian: 'мама', kazakh: 'ана', category: 'Family', descriptionRu: 'Женщина, которая родила тебя', descriptionKz: 'Сені туған әйел' },
  { english: 'father', russian: 'папа', kazakh: 'әке', category: 'Family', descriptionRu: 'Мужчина, твой родитель', descriptionKz: 'Ер адам, сенің ата-анаң' },
  { english: 'sister', russian: 'сестра', kazakh: 'қарындас', category: 'Family', descriptionRu: 'Девочка, дочь твоих родителей', descriptionKz: 'Қыз, сенің ата-анаңның қызы' },
  { english: 'brother', russian: 'брат', kazakh: 'аға', category: 'Family', descriptionRu: 'Мальчик, сын твоих родителей', descriptionKz: 'Бала, сенің ата-анаңның ұлы' },
  { english: 'baby', russian: 'малыш', kazakh: 'нәресте', category: 'Family', descriptionRu: 'Очень маленький ребёнок', descriptionKz: 'Өте кішкентай бала' },
  { english: 'grandma', russian: 'бабушка', kazakh: 'әже', category: 'Family', descriptionRu: 'Мама твоей мамы или папы', descriptionKz: 'Сенің анаң немесе әкең��ң анасы' },
  { english: 'grandpa', russian: 'дедушка', kazakh: 'ата', category: 'Family', descriptionRu: 'Папа твоей мамы или папы', descriptionKz: 'Сенің анаң немесе әкеңнің әкесі' },
  { english: 'parents', russian: 'родители', kazakh: 'ата-ана', category: 'Family', descriptionRu: 'Мама и папа вместе', descriptionKz: 'Ана мен әке бірге' },
  { english: 'child', russian: 'ребенок', kazakh: 'бала', category: 'Family', descriptionRu: 'Сын или дочь', descriptionKz: 'Ұл немесе қыз' },
  { english: 'son', russian: 'сын', kazakh: 'ұл', category: 'Family', descriptionRu: 'Мальчик, чей-то ребёнок', descriptionKz: 'Бала, біреудің баласы' },
  { english: 'daughter', russian: 'дочь', kazakh: 'қыз', category: 'Family', descriptionRu: 'Девочка, чья-то дочка', descriptionKz: 'Қыз, біреудің қызы' },
  { english: 'aunt', russian: 'тетя', kazakh: 'тәте', category: 'Family', descriptionRu: 'Сестра мамы или папы', descriptionKz: 'Ана немесе әкенің қарындасы' },
  { english: 'uncle', russian: 'дядя', kazakh: 'ағай', category: 'Family', descriptionRu: 'Брат мамы или папы', descriptionKz: 'Ана немесе әкенің ағасы' },
  { english: 'cousin', russian: 'двоюродный брат', kazakh: 'нағашы', category: 'Family', descriptionRu: 'Ребёнок тёти или дяди', descriptionKz: 'Тәте немесе ағайдың баласы' },
  { english: 'husband', russian: 'муж', kazakh: 'күйеу', category: 'Family', descriptionRu: 'Мужчина в браке', descriptionKz: 'Үйленген ер адам' },
  { english: 'wife', russian: 'жена', kazakh: 'әйел', category: 'Family', descriptionRu: 'Женщина в браке', descriptionKz: 'Үйленген әйел' },
  { english: 'family', russian: 'семья', kazakh: 'отбасы', category: 'Family', descriptionRu: 'Все родственники вместе', descriptionKz: 'Барлық туыстар бірге' },
  { english: 'twins', russian: 'близнецы', kazakh: 'егіздер', category: 'Family', descriptionRu: 'Два ребёнка, родившиеся вместе', descriptionKz: 'Бірге туған екі бала' },
  { english: 'nephew', russian: 'племянник', kazakh: 'жиен', category: 'Family', descriptionRu: 'Сын брата или сестры', descriptionKz: 'Аға немесе қарындастың ұлы' },
  { english: 'niece', russian: 'племянница', kazakh: 'жиен қыз', category: 'Family', descriptionRu: 'Дочь брата или сестры', descriptionKz: 'Аға немесе қарындастың қызы' },

  // Body - 30 слов
  { english: 'head', russian: 'голова', kazakh: 'бас', category: 'Body', descriptionRu: 'Верхняя часть тела с мозгом', descriptionKz: 'Дененің миы бар жоғарғы бөлігі' },
  { english: 'hair', russian: 'волосы', kazakh: 'шаш', category: 'Body', descriptionRu: 'Растёт на голове', descriptionKz: 'Баста өседі' },
  { english: 'face', russian: 'лицо', kazakh: 'бет', category: 'Body', descriptionRu: 'Передняя часть головы', descriptionKz: 'Бастың алдыңғы бөлігі' },
  { english: 'eye', russian: 'глаз', kazakh: 'көз', category: 'Body', descriptionRu: 'Орган, которым мы видим', descriptionKz: 'Көретін орган' },
  { english: 'ear', russian: 'ухо', kazakh: 'құлақ', category: 'Body', descriptionRu: 'Орган, которым мы слышим', descriptionKz: 'Естітін орган' },
  { english: 'nose', russian: 'нос', kazakh: 'мұрын', category: 'Body', descriptionRu: 'Орган, которым мы дышим и нюхаем', descriptionKz: 'Тыныс алатын және иіс сезетін орган' },
  { english: 'mouth', russian: 'рот', kazakh: 'ауыз', category: 'Body', descriptionRu: 'Орган, которым мы едим и говорим', descriptionKz: 'Жейтін және сөйлейтін орган' },
  { english: 'tooth', russian: 'зуб', kazakh: 'тіс', category: 'Body', descriptionRu: 'Белые кости во рту для жевания', descriptionKz: 'Ауыздағы шайнауға арналған ақ сүйектер' },
  { english: 'tongue', russian: 'язык', kazakh: 'тіл', category: 'Body', descriptionRu: 'Орган во рту для вкуса', descriptionKz: 'Ауыздағы дәм сезетін орган' },
  { english: 'neck', russian: 'шея', kazakh: 'мойын', category: 'Body', descriptionRu: 'Соединяет голову с телом', descriptionKz: 'Бас пен денені жалғайды' },
  { english: 'shoulder', russian: 'плечо', kazakh: 'иық', category: 'Body', descriptionRu: 'Место, где рука соединяется с телом', descriptionKz: 'Қолдың денеге жалғасатын жері' },
  { english: 'arm', russian: 'рука', kazakh: 'қол', category: 'Body', descriptionRu: 'Часть тела от плеча до кисти', descriptionKz: 'Иықтан алақанға дейінгі дене бөлігі' },
  { english: 'hand', russian: 'кисть руки', kazakh: 'алақан', category: 'Body', descriptionRu: 'Часть руки с пальцами', descriptionKz: 'Қолдың саусақтары бар бөлігі' },
  { english: 'finger', russian: 'палец', kazakh: 'саусақ', category: 'Body', descriptionRu: 'На руке их пять', descriptionKz: 'Қолда олардың бесеуі' },
  { english: 'thumb', russian: 'большой палец', kazakh: 'бас бармақ', category: 'Body', descriptionRu: 'Самый толстый палец на руке', descriptionKz: 'Қолдағы ең жуан саусақ' },
  { english: 'chest', russian: 'грудь', kazakh: 'кеуде', category: 'Body', descriptionRu: 'Передняя часть тела с сердцем', descriptionKz: 'Дененің жүрегі бар алдыңғы бөлігі' },
  { english: 'back', russian: 'спина', kazakh: 'арқа', category: 'Body', descriptionRu: 'Задняя часть тела', descriptionKz: 'Дененің артқы бөлігі' },
  { english: 'stomach', russian: 'живот', kazakh: 'қарын', category: 'Body', descriptionRu: 'Часть тела, куда попадает еда', descriptionKz: 'Тамақ түсетін дене бөлігі' },
  { english: 'leg', russian: 'нога', kazakh: 'аяқ', category: 'Body', descriptionRu: 'Часть тела для ходьбы', descriptionKz: 'Жүруге арналған дене бөлігі' },
  { english: 'knee', russian: 'колено', kazakh: 'тізе', category: 'Body', descriptionRu: 'Сустав в середине ноги', descriptionKz: 'Аяқтың ортасындағы буын' },
  { english: 'foot', russian: 'ступня', kazakh: 'табан', category: 'Body', descriptionRu: 'Нижняя часть ноги', descriptionKz: 'Аяқтың төменгі бөлігі' },
  { english: 'toe', russian: 'палец ноги', kazakh: 'аяқ саусағы', category: 'Body', descriptionRu: 'На ступне их пять', descriptionKz: 'Табанда олардың бесеуі' },
  { english: 'heart', russian: 'сердце', kazakh: 'жүрек', category: 'Body', descriptionRu: 'Орган, который качает кровь', descriptionKz: 'Қанды айдайтын орган' },
  { english: 'brain', russian: 'мозг', kazakh: 'ми', category: 'Body', descriptionRu: 'Орган, которым мы думаем', descriptionKz: 'Ойлайтын орган' },
  { english: 'skin', russian: 'кожа', kazakh: 'тері', category: 'Body', descriptionRu: 'Покрывает всё тело', descriptionKz: 'Бүкіл денені жабады' },
  { english: 'bone', russian: 'кость', kazakh: 'сүйек', category: 'Body', descriptionRu: 'Твёрдая часть внутри тела', descriptionKz: 'Дененің ішіндегі қатты бөлік' },
  { english: 'blood', russian: 'кровь', kazakh: 'қан', category: 'Body', descriptionRu: 'Красная жидкость в теле', descriptionKz: 'Денедегі қызыл сұйықтық' },
  { english: 'elbow', russian: 'локоть', kazakh: 'шынтақ', category: 'Body', descriptionRu: 'Сустав в середине руки', descriptionKz: 'Қолдың ортасындағы буын' },
  { english: 'wrist', russian: 'запястье', kazakh: 'білек', category: 'Body', descriptionRu: 'Соединяет руку и кисть', descriptionKz: 'Қол мен алақанды жалғайды' },
  { english: 'ankle', russian: 'лодыжка', kazakh: 'өкше', category: 'Body', descriptionRu: 'Соединяет ногу и ступню', descriptionKz: 'Аяқ пен табанды жалғайды' },

  // Food - 30 слов
  { english: 'bread', russian: 'хлеб', kazakh: 'нан', category: 'Food', descriptionRu: 'Еда из муки, едим каждый день', descriptionKz: 'Ұннан жасалған, күн сайын жейтін тамақ' },
  { english: 'milk', russian: 'молоко', kazakh: 'сүт', category: 'Food', descriptionRu: 'Белый напиток от коровы', descriptionKz: 'Сиырдан алынатын ақ сусын' },
  { english: 'water', russian: 'вода', kazakh: 'су', category: 'Food', descriptionRu: 'Прозрачная жидкость для питья', descriptionKz: 'Ішуге арналған мөлдір сұйықтық' },
  { english: 'juice', russian: 'сок', kazakh: 'шырын', category: 'Food', descriptionRu: 'Сладкий напиток из фруктов', descriptionKz: 'Жемістен жасалған тәтті сусын' },
  { english: 'tea', russian: 'чай', kazakh: 'шай', category: 'Food', descriptionRu: 'Горячий напиток', descriptionKz: 'Ыстық сусын' },
  { english: 'coffee', russian: 'кофе', kazakh: 'кофе', category: 'Food', descriptionRu: 'Горький напиток для взрослых', descriptionKz: 'Үлкендерге арналған ащы сусын' },
  { english: 'egg', russian: 'яйцо', kazakh: 'жұмыртқа', category: 'Food', descriptionRu: 'Белое круглое от курицы', descriptionKz: 'Тауықтан алынатын ақ дөңгелек' },
  { english: 'meat', russian: 'мясо', kazakh: 'ет', category: 'Food', descriptionRu: 'Еда от животных', descriptionKz: 'Жануарлардан алынатын тамақ' },
  { english: 'chicken', russian: 'курица', kazakh: 'тауық', category: 'Food', descriptionRu: 'Мясо птицы', descriptionKz: 'Құс еті' },
  { english: 'fish', russian: 'рыба', kazakh: 'балық', category: 'Food', descriptionRu: 'Еда из моря или реки', descriptionKz: 'Теңіз немесе өзеннен алынатын тамақ' },
  { english: 'rice', russian: 'рис', kazakh: 'күріш', category: 'Food', descriptionRu: 'Белые маленькие зёрна', descriptionKz: 'Ақ кішкентай дәндер' },
  { english: 'pasta', russian: 'макароны', kazakh: 'макарон', category: 'Food', descriptionRu: 'Длинная еда из муки', descriptionKz: 'Ұннан жасалған ұзын тамақ' },
  { english: 'soup', russian: 'суп', kazakh: 'сорпа', category: 'Food', descriptionRu: 'Горячее жидкое блюдо', descriptionKz: 'Ыстық сұйық тағам' },
  { english: 'salad', russian: 'салат', kazakh: 'салат', category: 'Food', descriptionRu: 'Блюдо из свежих овощей', descriptionKz: 'Жаңа көкөністерден жасалған тағам' },
  { english: 'cheese', russian: 'сыр', kazakh: 'ірімшік', category: 'Food', descriptionRu: 'Жёлтая еда из молока', descriptionKz: 'Сүттен жасалған сары тамақ' },
  { english: 'butter', russian: 'масло', kazakh: 'май', category: 'Food', descriptionRu: 'Мягкая жёлтая еда для хлеба', descriptionKz: 'Нанға жағатын жұмсақ сары тамақ' },
  { english: 'sugar', russian: 'сахар', kazakh: 'қант', category: 'Food', descriptionRu: 'Сладкие белые кристаллы', descriptionKz: 'Тәтті ақ кристалдар' },
  { english: 'salt', russian: 'соль', kazakh: 'тұз', category: 'Food', descriptionRu: 'Белый порошок для вкуса', descriptionKz: 'Дәмге арналған ақ ұнтақ' },
  { english: 'pepper', russian: 'перец', kazakh: 'бұрыш', category: 'Food', descriptionRu: 'Острая приправа', descriptionKz: 'Өткір дәмдеуіш' },
  { english: 'cake', russian: 'торт', kazakh: 'торт', category: 'Food', descriptionRu: 'Сладкий десерт на праздник', descriptionKz: 'Мерекеге арналған тәтті десерт' },
  { english: 'cookie', russian: 'печенье', kazakh: 'печенье', category: 'Food', descriptionRu: 'Маленькое сладкое печенье', descriptionKz: 'Кішкентай тәтті печенье' },
  { english: 'candy', russian: 'конфета', kazakh: 'кәмпит', category: 'Food', descriptionRu: 'Маленькая сладость', descriptionKz: 'Кішкентай тәттілік' },
  { english: 'chocolate', russian: 'шоколад', kazakh: 'шоколад', category: 'Food', descriptionRu: 'Коричневая сладость', descriptionKz: 'Қоңыр тәттілік' },
  { english: 'ice cream', russian: 'мороженое', kazakh: 'балмұздақ', category: 'Food', descriptionRu: 'Холодный сладкий десерт', descriptionKz: 'Суық тәтті десерт' },
  { english: 'pizza', russian: 'пицца', kazakh: 'пицца', category: 'Food', descriptionRu: 'Круглое итальянское блюдо', descriptionKz: 'Дөңгелек итальян тағамы' },
  { english: 'hamburger', russian: 'гамбургер', kazakh: 'гамбургер', category: 'Food', descriptionRu: 'Бутерброд с котлетой', descriptionKz: 'Котлеті бар бутерброд' },
  { english: 'sandwich', russian: 'бутерброд', kazakh: 'бутерброд', category: 'Food', descriptionRu: 'Еда между двумя кусками хлеба', descriptionKz: 'Екі нан арасындағы тамақ' },
  { english: 'breakfast', russian: 'завтрак', kazakh: 'таңғы ас', category: 'Food', descriptionRu: 'Еда утром', descriptionKz: 'Таңертең жейтін тамақ' },
  { english: 'lunch', russian: 'обед', kazakh: 'түскі ас', category: 'Food', descriptionRu: 'Еда днём', descriptionKz: 'Күндіз жейтін тамақ' },
  { english: 'dinner', russian: 'ужин', kazakh: 'кешкі ас', category: 'Food', descriptionRu: 'Еда вечером', descriptionKz: 'Кешке жейтін тамақ' },

  // Fruits - 20 слов
  { english: 'apple', russian: 'яблоко', kazakh: 'алма', category: 'Fruits', descriptionRu: 'Круглый красный или зелёный фрукт', descriptionKz: 'Дөңгелек қызыл немесе жасыл жеміс' },
  { english: 'banana', russian: 'банан', kazakh: 'банан', category: 'Fruits', descriptionRu: 'Длинный жёлтый фрукт', descriptionKz: 'Ұзын сары жеміс' },
  { english: 'orange', russian: 'апельсин', kazakh: 'апельсин', category: 'Fruits', descriptionRu: 'Круглый оранжевый цитрус', descriptionKz: 'Дөңгелек сарғыш цитрус' },
  { english: 'grape', russian: 'виноград', kazakh: 'жүзім', category: 'Fruits', descriptionRu: 'Маленькие круглые ягоды на ветке', descriptionKz: 'Бұтақтағы кішкентай дөңгелек жидектер' },
  { english: 'strawberry', russian: 'клубника', kazakh: 'құлпынай', category: 'Fruits', descriptionRu: 'Красная сладкая ягода', descriptionKz: 'Қызыл тәтті жидек' },
  { english: 'watermelon', russian: 'арбуз', kazakh: 'қарбыз', category: 'Fruits', descriptionRu: 'Большой зелёный фрукт, красный внутри', descriptionKz: 'Үлкен жасыл, ішінде қызыл жеміс' },
  { english: 'melon', russian: 'дыня', kazakh: 'қауын', category: 'Fruits', descriptionRu: 'Жёлтый сладкий фрукт', descriptionKz: 'Сары тәтті жеміс' },
  { english: 'pear', russian: 'груша', kazakh: 'алмұрт', category: 'Fruits', descriptionRu: 'Фрукт похожий на лампочку', descriptionKz: 'Шамға ұқсас жеміс' },
  { english: 'peach', russian: 'персик', kazakh: 'шабдалы', category: 'Fruits', descriptionRu: 'Мягкий оранжевый фрукт', descriptionKz: 'Жұмсақ сарғыш жеміс' },
  { english: 'plum', russian: 'слива', kazakh: 'алхоры', category: 'Fruits', descriptionRu: 'Маленький фиолетовый фрукт', descriptionKz: 'Кішкентай күлгін жеміс' },
  { english: 'cherry', russian: 'вишня', kazakh: 'шие', category: 'Fruits', descriptionRu: 'Маленькая красная ягода с косточкой', descriptionKz: 'Шұңқыры бар кішкентай қызыл жидек' },
  { english: 'lemon', russian: 'лимон', kazakh: 'лимон', category: 'Fruits', descriptionRu: 'Кислый жёлтый цитрус', descriptionKz: 'Қышқыл сары цитрус' },
  { english: 'kiwi', russian: 'киви', kazakh: 'киви', category: 'Fruits', descriptionRu: 'Коричневый снаружи, зелёный внутри', descriptionKz: 'Сыртынан қоңыр, ішінен жасыл' },
  { english: 'mango', russian: 'манго', kazakh: 'манго', category: 'Fruits', descriptionRu: 'Тропический сладкий фрукт', descriptionKz: 'Тропикалық тәтті жеміс' },
  { english: 'pineapple', russian: 'ананас', kazakh: 'ананас', category: 'Fruits', descriptionRu: 'Жёлтый фрукт с колючей кожурой', descriptionKz: 'Тікенді қабығы бар сары жеміс' },
  { english: 'coconut', russian: 'кокос', kazakh: 'кокос', category: 'Fruits', descriptionRu: 'Большой коричневый орех с молоком', descriptionKz: 'Сүті бар үлкен қоңыр жаңғақ' },
  { english: 'apricot', russian: 'абрикос', kazakh: 'өрік', category: 'Fruits', descriptionRu: 'Маленький оранжевый фрукт', descriptionKz: 'Кішкентай сарғыш жеміс' },
  { english: 'raspberry', russian: 'малина', kazakh: 'таңқурай', category: 'Fruits', descriptionRu: 'Красная сладкая ягода', descriptionKz: 'Қызыл тәтті жидек' },
  { english: 'pomegranate', russian: 'гранат', kazakh: 'анар', category: 'Fruits', descriptionRu: 'Красный фрукт с зёрнышками', descriptionKz: 'Дәнді қызыл жеміс' },
  { english: 'avocado', russian: 'авокадо', kazakh: 'авокадо', category: 'Fruits', descriptionRu: 'Зелёный маслянистый фрукт', descriptionKz: 'Майлы жасыл жеміс' },

  // Vegetables - 20 слов
  { english: 'carrot', russian: 'морковь', kazakh: 'сәбіз', category: 'Vegetables', descriptionRu: 'Длинный оранжевый овощ', descriptionKz: 'Ұзын сарғыш көкөніс' },
  { english: 'potato', russian: 'картофель', kazakh: 'картоп', category: 'Vegetables', descriptionRu: 'Коричневый овощ под землёй', descriptionKz: 'Жер астындағы қоңыр көкөніс' },
  { english: 'tomato', russian: 'помидор', kazakh: 'қызанақ', category: 'Vegetables', descriptionRu: 'Круглый красный овощ', descriptionKz: 'Дөңгелек қызыл көкөніс' },
  { english: 'cucumber', russian: 'огурец', kazakh: 'қияр', category: 'Vegetables', descriptionRu: 'Длинный зелёный овощ', descriptionKz: 'Ұзын жасыл көкөніс' },
  { english: 'onion', russian: 'лук', kazakh: 'пияз', category: 'Vegetables', descriptionRu: 'Овощ, от которого плачут', descriptionKz: 'Жылататын көкөніс' },
  { english: 'garlic', russian: 'чеснок', kazakh: 'сарымсақ', category: 'Vegetables', descriptionRu: 'Белый острый овощ', descriptionKz: 'Ақ өткір көкөніс' },
  { english: 'pepper', russian: 'перец', kazakh: 'бұрыш', category: 'Vegetables', descriptionRu: 'Зелёный или красный овощ', descriptionKz: 'Жасыл немесе қызыл көкөніс' },
  { english: 'cabbage', russian: 'капуста', kazakh: 'қырыққабат', category: 'Vegetables', descriptionRu: 'Круглый зелёный овощ из листьев', descriptionKz: 'Жапырақтан тұратын дөңгелек жасыл көкөніс' },
  { english: 'lettuce', russian: 'салат', kazakh: 'салат', category: 'Vegetables', descriptionRu: 'Зелёные листья для салата', descriptionKz: 'Салатқа арналған жасыл жапырақтар' },
  { english: 'broccoli', russian: 'брокколи', kazakh: 'брокколи', category: 'Vegetables', descriptionRu: 'Зелёный овощ похожий на дерево', descriptionKz: 'Ағашқа ұқсас жасыл көкөніс' },
  { english: 'pumpkin', russian: 'тыква', kazakh: 'асқабақ', category: 'Vegetables', descriptionRu: 'Большой оранжевый овощ', descriptionKz: 'Үлкен сарғыш көкөніс' },
  { english: 'eggplant', russian: 'баклажан', kazakh: 'бадамжан', category: 'Vegetables', descriptionRu: 'Длинный фиолетовый овощ', descriptionKz: 'Ұзын күлгін көкөніс' },
  { english: 'corn', russian: 'кукуруза', kazakh: 'жүгері', category: 'Vegetables', descriptionRu: 'Жёлтые зёрна на початке', descriptionKz: 'Бастиектегі сары дәндер' },
  { english: 'peas', russian: 'горох', kazakh: 'бұршақ', category: 'Vegetables', descriptionRu: 'Маленькие зелёные шарики', descriptionKz: 'Кішкентай жасыл доптар' },
  { english: 'beans', russian: 'фасоль', kazakh: 'бұршақ', category: 'Vegetables', descriptionRu: 'Овощ в стручках', descriptionKz: 'Құрамасындағы көкөніс' },
  { english: 'spinach', russian: 'шпинат', kazakh: 'шпинат', category: 'Vegetables', descriptionRu: 'Тёмно-зелёные листья', descriptionKz: 'Қою жасыл жапырақтар' },
  { english: 'beetroot', russian: 'свекла', kazakh: 'қызылша', category: 'Vegetables', descriptionRu: 'Красный овощ для борща', descriptionKz: 'Борщқа арналған қызыл көкөніс' },
  { english: 'radish', russian: 'редис', kazakh: 'редис', category: 'Vegetables', descriptionRu: 'Маленький красный острый овощ', descriptionKz: 'Кішкентай қызыл өткір көкөніс' },
  { english: 'turnip', russian: 'репа', kazakh: 'шалғам', category: 'Vegetables', descriptionRu: 'Белый круглый овощ', descriptionKz: 'Ақ дөңгелек көкөніс' },
  { english: 'mushroom', russian: 'гриб', kazakh: 'саңырауқұлақ', category: 'Vegetables', descriptionRu: 'Растёт в лесу, похож на зонтик', descriptionKz: 'Орманда өседі, қолшатырға ұқсас' },

  // School - 20 слов
  { english: 'school', russian: 'школа', kazakh: 'мектеп', category: 'School', descriptionRu: 'Здание, где учатся дети', descriptionKz: 'Балалар оқитын ғимарат' },
  { english: 'teacher', russian: 'учитель', kazakh: 'мұғалім', category: 'School', descriptionRu: 'Человек, который учит детей', descriptionKz: 'Балаларды оқытатын адам' },
  { english: 'student', russian: 'ученик', kazakh: 'оқушы', category: 'School', descriptionRu: 'Ребёнок, который учится', descriptionKz: 'Оқитын бала' },
  { english: 'book', russian: 'книга', kazakh: 'кітап', category: 'School', descriptionRu: 'Много страниц с текстом', descriptionKz: 'Мәтіні бар көп беттер' },
  { english: 'pen', russian: 'ручка', kazakh: 'қалам', category: 'School', descriptionRu: 'Пишем чернилами', descriptionKz: 'Сиямен жазамыз' },
  { english: 'pencil', russian: 'карандаш', kazakh: 'қарындаш', category: 'School', descriptionRu: 'Пишем, можно стереть', descriptionKz: 'Жазамыз, өшіруге болады' },
  { english: 'eraser', russian: 'ластик', kazakh: 'өшіргіш', category: 'School', descriptionRu: 'Стирает карандаш', descriptionKz: 'Қарындашты өшіреді' },
  { english: 'ruler', russian: 'линейка', kazakh: 'сызғыш', category: 'School', descriptionRu: 'Инструмент для прямых линий', descriptionKz: 'Тура сызық сызуға арналған құрал' },
  { english: 'notebook', russian: 'тетрадь', kazakh: 'дәптер', category: 'School', descriptionRu: 'Пишем домашнюю работу', descriptionKz: 'Үй жұмысын жазамыз' },
  { english: 'desk', russian: 'парта', kazakh: 'парта', category: 'School', descriptionRu: 'Стол в классе для учеников', descriptionKz: 'Сыныптағы оқушыларға арналған үстел' },
  { english: 'chair', russian: 'стул', kazakh: 'орындық', category: 'School', descriptionRu: 'Сидим на нём', descriptionKz: 'Онда отырамыз' },
  { english: 'board', russian: 'доска', kazakh: 'тақта', category: 'School', descriptionRu: 'Учитель пишет на ней', descriptionKz: 'Мұғалім онда жазады' },
  { english: 'chalk', russian: 'мел', kazakh: 'бор', category: 'School', descriptionRu: 'Белый для письма на доске', descriptionKz: 'Тақтада жазуға арналған ақ' },
  { english: 'bag', russian: 'сумка', kazakh: 'сөмке', category: 'School', descriptionRu: 'Носим вещи', descriptionKz: 'Заттарды алып жүреміз' },
  { english: 'backpack', russian: 'рюкзак', kazakh: 'рюкзак', category: 'School', descriptionRu: 'Сумка на спину', descriptionKz: 'Арқаға арналған сөмке' },
  { english: 'lesson', russian: 'урок', kazakh: 'сабақ', category: 'School', descriptionRu: 'Время обучения в школе', descriptionKz: 'Мектептегі оқу уақыты' },
  { english: 'homework', russian: 'домашняя работа', kazakh: 'үй жұмысы', category: 'School', descriptionRu: 'Задание на дом', descriptionKz: 'Үйге берілген тапсырма' },
  { english: 'test', russian: 'тест', kazakh: 'тест', category: 'School', descriptionRu: 'Проверка знаний', descriptionKz: 'Білімді тексеру' },
  { english: 'classroom', russian: 'класс', kazakh: 'сынып', category: 'School', descriptionRu: 'Комната для уроков', descriptionKz: 'Сабаққа арналған бөлме' },
  { english: 'library', russian: 'библиотека', kazakh: 'кітапхана', category: 'School', descriptionRu: 'Место с много книгами', descriptionKz: 'Көп кітап бар орын' },

  // Home - 30 слов
  { english: 'house', russian: 'дом', kazakh: 'үй', category: 'Home', descriptionRu: 'Здание, где мы живём', descriptionKz: 'Біз өмір сүретін ғимарат' },
  { english: 'room', russian: 'комната', kazakh: 'бөлме', category: 'Home', descriptionRu: 'Часть дома', descriptionKz: 'Үйдің бөлігі' },
  { english: 'door', russian: 'дверь', kazakh: 'есік', category: 'Home', descriptionRu: 'Открываем и закрываем для входа', descriptionKz: 'Кіру үшін ашамыз және жабамыз' },
  { english: 'window', russian: 'окно', kazakh: 'терезе', category: 'Home', descriptionRu: 'Смотрим на улицу через него', descriptionKz: 'Одан көше қарай қараймыз' },
  { english: 'wall', russian: 'стена', kazakh: 'қабырға', category: 'Home', descriptionRu: 'Вертикальная часть комнаты', descriptionKz: 'Бөлменің тік бөлігі' },
  { english: 'floor', russian: 'пол', kazakh: 'еден', category: 'Home', descriptionRu: 'Нижняя часть комнаты, ходим по нему', descriptionKz: 'Бөлменің төменгі бөлігі, онда жүреміз' },
  { english: 'ceiling', russian: 'потолок', kazakh: 'төбе', category: 'Home', descriptionRu: 'Верхняя часть комнаты', descriptionKz: 'Бөлменің жоғарғы бөлігі' },
  { english: 'roof', russian: 'крыша', kazakh: 'шатыр', category: 'Home', descriptionRu: 'Верх дома, защищает от дождя', descriptionKz: 'Үйдің үсті, жаңбырдан қорғайды' },
  { english: 'bed', russian: 'кровать', kazakh: 'төсек', category: 'Home', descriptionRu: 'Мебель для сна', descriptionKz: 'Ұйықтауға арналған жиһаз' },
  { english: 'table', russian: 'стол', kazakh: 'үстел', category: 'Home', descriptionRu: 'Мебель с плоской поверхностью', descriptionKz: 'Жалпақ бетті жиһаз' },
  { english: 'chair', russian: 'стул', kazakh: 'орындық', category: 'Home', descriptionRu: 'Мебель для сидения', descriptionKz: 'Отыруға арналған жиһаз' },
  { english: 'sofa', russian: 'диван', kazakh: 'диван', category: 'Home', descriptionRu: 'Мягкая мебель для нескольких человек', descriptionKz: 'Бірнеше адамға арналған жұмсақ жиһаз' },
  { english: 'lamp', russian: 'лампа', kazakh: 'шам', category: 'Home', descriptionRu: 'Даёт свет', descriptionKz: 'Жарық береді' },
  { english: 'mirror', russian: 'зеркало', kazakh: 'айна', category: 'Home', descriptionRu: 'Видим своё отражение', descriptionKz: 'Өз бейнемізді көреміз' },
  { english: 'clock', russian: 'часы', kazakh: 'сағат', category: 'Home', descriptionRu: 'Показывает время', descriptionKz: 'Уақытты көрсетеді' },
  { english: 'picture', russian: 'картина', kazakh: 'сурет', category: 'Home', descriptionRu: 'Висит на стене для красоты', descriptionKz: 'Әдемілік үшін қабырғада тұрады' },
  { english: 'television', russian: 'телевизор', kazakh: 'теледидар', category: 'Home', descriptionRu: 'Смотрим фильмы и передачи', descriptionKz: 'Фильмдер мен хабарларды қараймыз' },
  { english: 'computer', russian: 'компьютер', kazakh: 'компьютер', category: 'Home', descriptionRu: 'Работаем и играем на нём', descriptionKz: 'Онда жұмыс істейміз және ойнаймыз' },
  { english: 'phone', russian: 'телефон', kazakh: 'телефон', category: 'Home', descriptionRu: 'Звоним и пишем сообщения', descriptionKz: 'Қоңырау шаламыз және хабарлама жазамыз' },
  { english: 'refrigerator', russian: 'холодильник', kazakh: 'тоңазытқыш', category: 'Home', descriptionRu: 'Хранит еду холодной', descriptionKz: 'Тамақты салқындатып сақтайды' },
  { english: 'stove', russian: 'плита', kazakh: 'пеш', category: 'Home', descriptionRu: 'Готовим на ней еду', descriptionKz: 'Онда тамақ әзірлейміз' },
  { english: 'sink', russian: 'раковина', kazakh: 'раковина', category: 'Home', descriptionRu: 'Моем руки и посуду', descriptionKz: 'Қол мен ыдысты жуамыз' },
  { english: 'toilet', russian: 'туалет', kazakh: 'дәретхана', category: 'Home', descriptionRu: 'Комната гигиены', descriptionKz: 'Гигиена бөлмесі' },
  { english: 'shower', russian: 'душ', kazakh: 'душ', category: 'Home', descriptionRu: 'Моемся под водой', descriptionKz: 'Судың астында жуынамыз' },
  { english: 'bathtub', russian: 'ванна', kazakh: 'ванна', category: 'Home', descriptionRu: 'Большая для купания', descriptionKz: 'Жуынуға арналған үлкен' },
  { english: 'towel', russian: 'полотенце', kazakh: 'сүлгі', category: 'Home', descriptionRu: 'Вытираемся после душа', descriptionKz: 'Душтан кейін сүртеміз' },
  { english: 'soap', russian: 'мыло', kazakh: 'сабын', category: 'Home', descriptionRu: 'Моем руки с ним', descriptionKz: 'Онымен қол жуамыз' },
  { english: 'toothbrush', russian: 'зубная щетка', kazakh: 'тіс щеткасы', category: 'Home', descriptionRu: 'Чистим зубы', descriptionKz: 'Тісті тазалаймыз' },
  { english: 'blanket', russian: 'одеяло', kazakh: 'көрпе', category: 'Home', descriptionRu: 'Укрываемся, чтобы было тепло', descriptionKz: 'Жылу үшін жабынамыз' },
  { english: 'pillow', russian: 'подушка', kazakh: 'жастық', category: 'Home', descriptionRu: 'Мягкое для головы во время сна', descriptionKz: 'Ұйықтағанда бас үшін жұмсақ' },
];

// Получить все категории
export function getCategories(): string[] {
  const categories = new Set(BEGINNER_WORDS.map(w => w.category));
  return Array.from(categories).sort();
}

// Получить слова по категории
export function getWordsByCategory(category: string): Word[] {
  return BEGINNER_WORDS.filter(w => w.category === category);
}

// Получить общее количество слов
export function getTotalWords(): number {
  return BEGINNER_WORDS.length;
}
